"""Exact occupation -> category overrides, checked before the pattern rules."""


# Explicit overrides for occupations the regex rules misclassify.
CATEGORY_OVERRIDES = {
    # technology; bare "DEVELOPER" in FEC data is usually software
    "SOFTWARE DEVELOPER": "TECHNOLOGY",
    "SOFTWARE EXECUTIVE": "TECHNOLOGY",
    "SOFTWARE RELEASE ANALYST": "TECHNOLOGY",
    "SOFTWARE DEVELOPMENT MANAGER": "TECHNOLOGY",
    "QUANT DEVELOPER": "TECHNOLOGY",
    "DEVELOPER": "TECHNOLOGY",
    "DEVELOPER/DESIGNER": "TECHNOLOGY",
    "DATABASE DEVELOPER": "TECHNOLOGY",
    "DATABASE ANALYTICS": "TECHNOLOGY",

    # construction / trades; CONTRACTOR is caught by the EXECUTIVE regex
    "CONTRACTOR": "CONSTRUCTION / TRADES",
    "GENERAL CONTRACTOR": "CONSTRUCTION / TRADES",
    "ELECTRICAL CONTRACTOR": "CONSTRUCTION / TRADES",
    "ROOFING CONTRACTOR": "CONSTRUCTION / TRADES",
    "FLOORING CONTRACTOR": "CONSTRUCTION / TRADES",
    "FLOORING": "CONSTRUCTION / TRADES",
    "ARCHITECT": "CONSTRUCTION / TRADES",
    "INTERIOR ARCHITECT": "CONSTRUCTION / TRADES",

    # CHIROPRACTOR also caught by the EXECUTIVE regex
    "CHIROPRACTOR": "MEDICAL / HEALTHCARE",

    # Titles that only reached EXECUTIVE / C-SUITE through CEO/CDO/CTO/CIO
    # letters inside another word, before those were made whole-word.
    # INDEPENDENT CONTRACTOR is a work arrangement like FREELANCER, not a
    # trade; the PRIVATE MUSIC one teaches music for a park district.
    "INDEPENDENT CONTRACTOR": "SELF-EMPLOYED",
    "INDEPENDENT CONTRACTOR- PRIVATE MUSIC": "ARTS / ENTERTAINMENT",
    "VOICEOVER/AUDO PRODUCTION": "ARTS / ENTERTAINMENT",
    # AWS job code: Data Center Engineering Operations technician, level IV
    "DCEO EOT IV": "TECHNOLOGY",
    # virtual Chief Information Officer: a real C-level title, kept
    "VCIO": "EXECUTIVE / C-SUITE",
    "NURSING COORDINATOR": "MEDICAL / HEALTHCARE",
    "CLINICAL NURSING COORDINATOR": "MEDICAL / HEALTHCARE",
    # same bucket as CUSTOMER SERVICE / CUSTOMER SUCCESS and RECRUITER
    "CUSTOMER ENGAGEMENT COORDINATOR": "SALES / MARKETING",
    "RECRUITING COORDINATOR": "SALES / MARKETING",

    # finance
    "PRIVATE WEALTH ADVISOR": "FINANCE / INVESTMENT",
    "FUND MANAGER": "FINANCE / INVESTMENT",
    "MONEY MANAGEMENT": "FINANCE / INVESTMENT",
    "MONEY MANAGER": "FINANCE / INVESTMENT",
    "ECONOMIST": "FINANCE / INVESTMENT",
    "CFP": "FINANCE / INVESTMENT",

    # sales / marketing
    "BUSINESS DEVELOPMENT MANAGER": "SALES / MARKETING",
    "BUSINESS DEVELOPMENT": "SALES / MARKETING",
    "HEAD OF BUSINESS DEVELOPMENT": "SALES / MARKETING",
    "ACCOUNT EXECUTIVE": "SALES / MARKETING",

    # management
    "HUMAN RESOURCES": "MANAGEMENT",
    "CONSTRUCTION MANAGER": "MANAGEMENT",

    # executive
    "VP OF MARKETING": "EXECUTIVE / C-SUITE",
    "CHIEF DEVELOPMENT OFFICER": "EXECUTIVE / C-SUITE",

    # legal; MEDIATION contains MEDIA so the SALES/MARKETING regex fires
    "MEDIATION": "LEGAL",
    "MEDIATOR": "LEGAL",
    "FAMILY MEDIATION": "LEGAL",
    "FAMILY MEDIATOR": "LEGAL",

    "RESTAURATEUR": "FOOD / HOSPITALITY",
    "EDUCATION": "EDUCATION",

    # real estate development
    "OWNER/DEVELOPER": "REAL ESTATE",
    "PROPERTY DEVELOPMENT": "REAL ESTATE",
    "SOLAR DEVELOPER": "CONSTRUCTION / TRADES",
    "AFFORDABLE HOUSING DEVELOPER": "REAL ESTATE",

    # medical, missed by regex
    "NEPHROLOGIST": "MEDICAL / HEALTHCARE",
    "PHARMACY SERVICES": "MEDICAL / HEALTHCARE",
    "PHARMACY": "MEDICAL / HEALTHCARE",
    "PHARMACIST CONSULTANT": "MEDICAL / HEALTHCARE",
    "ORAL SURGEON": "MEDICAL / HEALTHCARE",
    "ALLERGIST": "MEDICAL / HEALTHCARE",
    "INTERNIST": "MEDICAL / HEALTHCARE",

    # government, missed by regex
    "COUNCILMEMBER": "GOVERNMENT / MILITARY",
    "CITY COUNCIL MEMBER": "GOVERNMENT / MILITARY",
    "COUNCIL MEMBER": "GOVERNMENT / MILITARY",
    "ELECTED OFFICIAL": "GOVERNMENT / MILITARY",
    "PUBLIC OFFICIAL": "GOVERNMENT / MILITARY",
    "MAYOR": "GOVERNMENT / MILITARY",
    "ALDERMAN": "GOVERNMENT / MILITARY",

    "PROPANE MARKETER": "SALES / MARKETING",
    "IMPORTER": "SALES / MARKETING",

    # real estate development variants
    "COMMERCIAL REAL ESTATE DEVELOPMENT": "REAL ESTATE",
    "REAL ESTATE DEVELOPMENT AND MANAGEMENT": "REAL ESTATE",
    "HOUSING DEVELOPMENT": "REAL ESTATE",
    "HOMELESS HOUSING": "REAL ESTATE",
    "COMMUNITY BUILDING": "REAL ESTATE",

    # executive typos and variants
    "CORP EXEC": "EXECUTIVE / C-SUITE",
    "EXEC VP": "EXECUTIVE / C-SUITE",
    "EXECUIVE": "EXECUTIVE / C-SUITE",
    "CORPORATE OFFICER": "EXECUTIVE / C-SUITE",
    "SENIOR ASSOCIATE": "EXECUTIVE / C-SUITE",
    "MANAGING MENBER": "EXECUTIVE / C-SUITE",
    "CORPORATE FIDUCIARY": "EXECUTIVE / C-SUITE",

    "CONSULTANCY": "CONSULTING",

    # arts / entertainment
    "ART GALLERIST": "ARTS / ENTERTAINMENT",
    "ENTERTAINER": "ARTS / ENTERTAINMENT",
    "DECORATOR": "ARTS / ENTERTAINMENT",
    "CORPORATE STORYTELLER": "ARTS / ENTERTAINMENT",
    "TOUR GUIDE": "ARTS / ENTERTAINMENT",
    "SUSTAINABLE DESIGN": "ARTS / ENTERTAINMENT",
    "MEETING PLANNER": "ARTS / ENTERTAINMENT",
    "INTERNATIONAL PARTY PLANNER": "ARTS / ENTERTAINMENT",

    # business
    "AUTOMOBILE DEALER": "BUSINESS / ENTREPRENEUR",
    "RETAILER": "BUSINESS / ENTREPRENEUR",
    "LUMBER BIZ": "BUSINESS / ENTREPRENEUR",
    "BUSIENSS": "BUSINESS / ENTREPRENEUR",
    "INTERNATIONAL COMMERCE": "BUSINESS / ENTREPRENEUR",
    "APARTMENTS": "REAL ESTATE",
    "HOMEBUILDING": "CONSTRUCTION / TRADES",

    # education
    "DEAN": "EDUCATION",
    "TEACHING": "EDUCATION",
    "STUDENT CUSTODIAN": "EDUCATION",

    # medical
    "REGISTERED DIETITIAN": "MEDICAL / HEALTHCARE",
    "HOLISTIC NUTRITIONIST": "MEDICAL / HEALTHCARE",
    "HEALTH COCH": "MEDICAL / HEALTHCARE",
    "CAREGIVER": "MEDICAL / HEALTHCARE",
    "CLINICAL DEVELOPMENT": "MEDICAL / HEALTHCARE",

    # management
    "MANAGET": "MANAGEMENT",
    "PROJECT MGR": "MANAGEMENT",
    "ACCOUNT CLERK": "MANAGEMENT",
    "OFFICE HELP": "MANAGEMENT",
    "PROP MNGMT": "MANAGEMENT",
    "RGM LEAD": "MANAGEMENT",

    "SW EGIEER": "TECHNOLOGY",
    "APP DEVELOPMENT": "TECHNOLOGY",

    # finance
    "GROWTH EQUITY": "FINANCE / INVESTMENT",
    "VENTURE CSPITALIST": "FINANCE / INVESTMENT",
    "UNDERWRITING": "FINANCE / INVESTMENT",

    "MARKETER": "SALES / MARKETING",

    # government
    "PUBLIC ADJUSTER": "GOVERNMENT / MILITARY",
    "PROGRAM SPECIALIST": "GOVERNMENT / MILITARY",
    "COMP CLAIMS REFEREE": "GOVERNMENT / MILITARY",
    "INFORMATION RESEARCH SPECIALIST": "GOVERNMENT / MILITARY",
    "JUDICIAL RECEIVER": "LEGAL",

    "FREELANCER": "SELF-EMPLOYED",
    "PET SITTER": "SELF-EMPLOYED",

    # batch 2

    # executive
    "DEPUTY MANAGING DIRECTOR": "EXECUTIVE / C-SUITE",
    "CO PRES": "EXECUTIVE / C-SUITE",
    "FOOD MFG EXEC": "EXECUTIVE / C-SUITE",
    "CH BD": "EXECUTIVE / C-SUITE",
    "EXEC RECRUITING/BD": "EXECUTIVE / C-SUITE",
    "SVP, MUSIC & CELEBRITY TALENT": "EXECUTIVE / C-SUITE",
    "FIN MGMT": "FINANCE / INVESTMENT",
    "FIN ADV": "FINANCE / INVESTMENT",
    "FINACIAL": "FINANCE / INVESTMENT",
    "PRIVATE WEALTH": "FINANCE / INVESTMENT",
    "PRIVATE CREDIT ALLOCATOR": "FINANCE / INVESTMENT",
    "RESTRUCTURING": "FINANCE / INVESTMENT",
    "AQUISITIONS": "FINANCE / INVESTMENT",
    "FUNDING": "FINANCE / INVESTMENT",

    # legal
    "ATROENEY": "LEGAL",
    "ATTOENY": "LEGAL",
    "ATT'Y": "LEGAL",
    "PROSECUTOR": "LEGAL",
    "FIDUCIARY": "LEGAL",

    # medical / science
    "NUCLEAR HYDROLOGIST": "SCIENCE / RESEARCH",
    "BIOSTATISTICIAN": "SCIENCE / RESEARCH",
    # the lead researcher on a grant or trial (NIH term); without this it
    # falls to EXECUTIVE through PRINCIPAL now that INVEST no longer claims it
    "PRINCIPAL INVESTIGATOR": "SCIENCE / RESEARCH",
    "PSYCHOMETRIST": "MEDICAL / HEALTHCARE",
    "LONG TERM CARE AND REHABILITATION FACI": "MEDICAL / HEALTHCARE",
    "SENIOR LIVING": "MEDICAL / HEALTHCARE",
    "MENTAL HEALTH": "MEDICAL / HEALTHCARE",
    "CLINICAL TRIALS": "MEDICAL / HEALTHCARE",
    "HESLTHCARE": "MEDICAL / HEALTHCARE",
    "PHYT": "MEDICAL / HEALTHCARE",

    # insurance
    "INSURANCE BROKER": "INSURANCE",
    "INSURANCE": "INSURANCE",
    "COMPLEX CLAIMS SPECIALIST": "INSURANCE",
    "ADJUSTER": "INSURANCE",

    # real estate
    "REAL ESTATE": "REAL ESTATE",
    "REAL EATSTE": "REAL ESTATE",
    "REAL ESTATE DEVELOPMENT": "REAL ESTATE",
    "CRE APPRAISER": "REAL ESTATE",
    "APPRAISER": "REAL ESTATE",
    "MARINA OPERATOR": "REAL ESTATE",
    "SELF STG MGMT & DVLPMT": "REAL ESTATE",
    "HOME IMPROVEMENT": "CONSTRUCTION / TRADES",

    # sales / marketing
    "MARKEITNG": "SALES / MARKETING",
    "BRANDING": "SALES / MARKETING",
    "BRANDED MERCH": "SALES / MARKETING",
    "MERCH AND PROMOTIONAL PRODUCTS": "SALES / MARKETING",
    "HEADHUNTER": "SALES / MARKETING",
    "CUSTOMER SERVICE": "SALES / MARKETING",
    "LOAN OFFICER": "SALES / MARKETING",
    "AUCTIONEER": "SALES / MARKETING",

    # education
    "INSTRUCTIONAL COACH": "EDUCATION",
    "LANG ARTS SPECIALIST": "EDUCATION",
    "BASKETBALL COACH": "EDUCATION",
    "GRAD STUDENT": "STUDENT",
    "SENIOR FELLOW": "EDUCATION",
    # roster title (Heritage Foundation): a think-tank fellow like SENIOR
    # FELLOW, not a lawyer (COUNSELOR) nor a company president (PRESIDENT)
    "SENIOR COUNSELOR TO THE PRESIDENT AND E.W. RICHARDSON FELLOW": "EDUCATION",

    # management
    "PRODUCT MANAGEENT": "MANAGEMENT",
    "PROGRAM ASSOCIATE": "MANAGEMENT",
    "OPS": "MANAGEMENT",
    "PACKAGE HANDLER": "MANAGEMENT",
    "CLERK": "MANAGEMENT",
    "OFFICE STAFF": "MANAGEMENT",
    "OPERATOR": "MANAGEMENT",
    "EMPLOYEE": "MANAGEMENT",
    "MANAY": "MANAGEMENT",
    "MD LATAM": "MANAGEMENT",

    # government
    "CONGRESSIONAL CANDIDATE": "GOVERNMENT / MILITARY",
    "STATE REP": "GOVERNMENT / MILITARY",
    "JP #5": "GOVERNMENT / MILITARY",
    "GOV'T RELATIONS": "GOVERNMENT / MILITARY",
    "LANDMAN": "GOVERNMENT / MILITARY",

    # arts / entertainment
    "HAIR STYLIST": "ARTS / ENTERTAINMENT",
    "FLORIST": "ARTS / ENTERTAINMENT",
    "TAILOR": "ARTS / ENTERTAINMENT",
    "VIDEO": "ARTS / ENTERTAINMENT",
    "BROADCAST PRODUCTION": "ARTS / ENTERTAINMENT",
    "FIELD PROD": "ARTS / ENTERTAINMENT",
    "PRODUCT DESIGN": "ARTS / ENTERTAINMENT",
    "MULTI FAMILY DESIGN": "ARTS / ENTERTAINMENT",
    "YOGA FITNESS": "ARTS / ENTERTAINMENT",
    "LIFE COACH": "CONSULTING",
    "MARRIAGE COACH": "CONSULTING",
    "FACILITATOR": "CONSULTING",

    # business
    "AUTO": "BUSINESS / ENTREPRENEUR",
    "AUTOMTIVE": "BUSINESS / ENTREPRENEUR",
    "IMPORT": "BUSINESS / ENTREPRENEUR",
    "SCRAP": "BUSINESS / ENTREPRENEUR",
    "PAPER CONVERTER": "BUSINESS / ENTREPRENEUR",
    "APPAREL": "BUSINESS / ENTREPRENEUR",
    "JEWLERY": "BUSINESS / ENTREPRENEUR",
    # keyed on the corrected spelling: OCCUPATION_NORMALIZE already rewrites
    # the raw CLEANNG SERVICE, so a typo key here could never match
    "CLEANING SERVICE": "BUSINESS / ENTREPRENEUR",
    "ENERGY": "BUSINESS / ENTREPRENEUR",
    "POWER": "BUSINESS / ENTREPRENEUR",
    "OIL & GAS": "BUSINESS / ENTREPRENEUR",
    "DIGITAL TRANSFORMATION": "TECHNOLOGY",

    "ISRAEL TOUR OPERATOR": "FOOD / HOSPITALITY",

    # nonprofit
    "FUND-RAISING": "NONPROFIT / PHILANTHROPY",
    "JEWISH PROFESSIONAL": "NONPROFIT / PHILANTHROPY",
    "DIR OF PROGRAMMING": "NONPROFIT / PHILANTHROPY",
    "DIRECT OF CURRICULUM DEVELOPMENT": "EDUCATION",

    # science
    "MEMBER OF RESEARCH STAFF": "SCIENCE / RESEARCH",
    "PSYCHOLOGY": "SCIENCE / RESEARCH",

    # batch 3: final stragglers
    "DEVELOPMENT": "NONPROFIT / PHILANTHROPY",  # fundraising context in this data
    "INTERNATIONAL DEVELOPMENT": "NONPROFIT / PHILANTHROPY",
    "VP OF DEVELOPMENT": "NONPROFIT / PHILANTHROPY",
    "INVESTMENT MANAGEMENT": "FINANCE / INVESTMENT",
    "MANAGING PARTNER": "EXECUTIVE / C-SUITE",
    "OWNER": "BUSINESS / ENTREPRENEUR",
    "ENTREPRENEUR": "BUSINESS / ENTREPRENEUR",
    "ATTORNEY": "LEGAL",
    "LAWYER": "LEGAL",
    "EMPLOYED": "OTHER",  # no info — keep as OTHER
    "SELF-EMPLOYED": "SELF-EMPLOYED",
    "REG. REP": "FINANCE / INVESTMENT",
    "GP": "FINANCE / INVESTMENT",  # General Partner
    "SALE": "SALES / MARKETING",
    "ACCOUNT": "ACCOUNTING / TAX",
    "MFG": "BUSINESS / ENTREPRENEUR",
    "VENTURER": "FINANCE / INVESTMENT",
    "HEALTH": "MEDICAL / HEALTHCARE",
    "PROGRAM": "MANAGEMENT",
    "ASSOC": "MANAGEMENT",
    "REGISTERED DIETITIAN, HEALTH AND WELLN": "MEDICAL / HEALTHCARE",
    "HOLISTIC WEALTH AND PHILANTHROPIC COAC": "CONSULTING",

    # Final audit: real, readable occupations that the broad regexes cannot
    # place reliably. Exact values keep these decisions easy to review.
    "ACQUISITIONS": "FINANCE / INVESTMENT",
    "ASSET MANAGER": "FINANCE / INVESTMENT",
    "CAPITAL MARKETS": "FINANCE / INVESTMENT",
    "CLAIMS": "INSURANCE",
    "CANDIDATE FOR DC DELEGATE TO CONGRESS": "GOVERNMENT / MILITARY",
    "COMMERCIAL RE AGENT": "REAL ESTATE",
    "DIRECTOR OF ADVANCEMENT": "NONPROFIT / PHILANTHROPY",
    "EVENT CURATOR": "ARTS / ENTERTAINMENT",
    "EVENT PLANNING": "ARTS / ENTERTAINMENT",
    "FILM AND TV": "ARTS / ENTERTAINMENT",
    "FILM PRODUCTION": "ARTS / ENTERTAINMENT",
    "FOUNDING MEMBER": "EXECUTIVE / C-SUITE",
    "FUND RAISING": "NONPROFIT / PHILANTHROPY",
    "HEALTH AND WELLNESS": "MEDICAL / HEALTHCARE",
    "KOI FISH HAIR STYLIST": "ARTS / ENTERTAINMENT",
    "LEADERSHIP COACHING": "CONSULTING",
    "LITIGATION NEUTRAL": "LEGAL",
    "MASTER TOUR GUIDE": "ARTS / ENTERTAINMENT",
    "NUTRITIONIST, ALBUM MAKING": "MEDICAL / HEALTHCARE",
    "PARAPROFESSIONAL": "EDUCATION",
    "PAYMENTS PROFESSIONAL": "FINANCE / INVESTMENT",
    "PAYROLL PROCESSING": "ACCOUNTING / TAX",
    "PROFESSIONAL SPEAKER": "ARTS / ENTERTAINMENT",
    "REGULATORY": "GOVERNMENT / MILITARY",
    "RESIDENTIAL CONNECTIVITY SPECIALIST": "TECHNOLOGY",
    "RETINA SURGERY": "MEDICAL / HEALTHCARE",
    "STEEL DISTRIBUTOR": "BUSINESS / ENTREPRENEUR",
    "TELECOM": "TECHNOLOGY",
    "VICE PRESIDENT, SHOWS": "EXECUTIVE / C-SUITE",
    "VICE PRESIDENT, TRADE SHOWS": "EXECUTIVE / C-SUITE",
    "WEALTH ADVISOR": "FINANCE / INVESTMENT",
    "WHOLESALE LUMBER": "BUSINESS / ENTREPRENEUR",

    # Readable one-off descriptions from the FEC data. Exact overrides avoid
    # broad regexes that could misclassify unrelated occupations.
    "DESIGN AND BUILD": "CONSTRUCTION / TRADES",
    "FOOD AND BEVERAGE CONSUMER RESEARCH": "SALES / MARKETING",
    "HOUSING": "REAL ESTATE",
    "INSTITUTIONAL DISTRIBUTION & CLIENT SE": "SALES / MARKETING",
    "INSTITUTIONAL DISTRIBUTION & CLIENT SERVICES": "SALES / MARKETING",
    "OWNERSHIP": "BUSINESS / ENTREPRENEUR",

    # 2026-09-23 audit: unambiguous job titles the regexes miss, each placed
    # beside an existing analogue (named in the comment). Deliberately left
    # OTHER because the word alone is ambiguous: INVESTIGATOR, COUNSELOR,
    # REPRESENTATIVE, TRUSTEE, NEUTRAL, SPEAKER, MAGICIAN, SUMMER ASSOCIATE,
    # FRAMING (carpentry or picture framing), ADVOCATE, PA, STRATEGY.
    # medical (PSYCHOPHARMACOLOGIST, NEPHROLOGIST, LMFT, PERSONAL TRAINER)
    "CLINICAL PSYCHOPHARMACOLOGIST": "MEDICAL / HEALTHCARE",
    "ELECTROPHYSIOLOGIST": "MEDICAL / HEALTHCARE",
    "HEPATOLOGIST": "MEDICAL / HEALTHCARE",
    "AUDIOLOGIST": "MEDICAL / HEALTHCARE",
    "PROSTHETIST": "MEDICAL / HEALTHCARE",
    "PROSTHODONTIST": "MEDICAL / HEALTHCARE",
    "CRNA": "MEDICAL / HEALTHCARE",
    "AMFT": "MEDICAL / HEALTHCARE",
    "ANESTHESIA": "MEDICAL / HEALTHCARE",
    "NURSING": "MEDICAL / HEALTHCARE",
    "OPTICIAN": "MEDICAL / HEALTHCARE",
    "MENTAL HEALTH CLINICIAN": "MEDICAL / HEALTHCARE",
    "OCCUPATIONAL HEALTH": "MEDICAL / HEALTHCARE",
    "HEALTH & WELLNESS COACH": "MEDICAL / HEALTHCARE",
    "HOLISTIC HEALTH & WELLNESS COACH": "MEDICAL / HEALTHCARE",
    "HOLISTIC HEALTH AND WELLNESS COACH": "MEDICAL / HEALTHCARE",
    "HOLISTIC NUTRITION": "MEDICAL / HEALTHCARE",
    "FITNESS TRAINER": "MEDICAL / HEALTHCARE",
    # arts / entertainment (POKER BROADCASTER, TAILOR, HAIR STYLIST, BEAUTY,
    # SPORTS, TOUR GUIDE, ART GALLERIST; interpreters and translators are BLS
    # SOC 27-3091, in the arts/media group)
    "NOVELIST": "ARTS / ENTERTAINMENT",
    "COMPOSER": "ARTS / ENTERTAINMENT",
    "SCULPTOR": "ARTS / ENTERTAINMENT",
    "PODCASTER": "ARTS / ENTERTAINMENT",
    "PODCAST COHOST": "ARTS / ENTERTAINMENT",
    "REPETITEUR": "ARTS / ENTERTAINMENT",
    "VFX": "ARTS / ENTERTAINMENT",
    "HAIRSTYLIST": "ARTS / ENTERTAINMENT",
    "HAIRDRESSER": "ARTS / ENTERTAINMENT",
    "PERSONAL STYLIST": "ARTS / ENTERTAINMENT",
    "ESTHETICIAN": "ARTS / ENTERTAINMENT",
    "DOCENT": "ARTS / ENTERTAINMENT",
    "ART GALLERY": "ARTS / ENTERTAINMENT",
    "INTERPRETER": "ARTS / ENTERTAINMENT",
    "TRANSLATOR": "ARTS / ENTERTAINMENT",
    "GLOBAL BROADCAST TALENT": "ARTS / ENTERTAINMENT",
    "EQUESTRIAN": "ARTS / ENTERTAINMENT",
    "HORSE TRAINER": "ARTS / ENTERTAINMENT",
    "ALTERATIONS SPECIALIST": "ARTS / ENTERTAINMENT",
    "BOOKBINDER": "ARTS / ENTERTAINMENT",
    # education (TRAINER, INSTRUCTIONAL COACH, EDUCATIONAL SPECIALIST)
    "ADJUNCT": "EDUCATION",
    "READING SPECIALIST": "EDUCATION",
    "ESSAY COACH": "EDUCATION",
    "EDUCATIONAL THERAPY": "EDUCATION",
    "EDUCATIONAL LIAISON": "EDUCATION",
    "CORPORATE TRAINER": "EDUCATION",
    "LEADERSHIP TRAINING": "EDUCATION",
    # consulting (LIFE COACH, MARRIAGE COACH, LEADERSHIP COACHING)
    "ADHD COACH": "CONSULTING",
    "CAREER COACHING": "CONSULTING",
    "CAREER LEADERSHIP COACH": "CONSULTING",
    "PARENT COACH": "CONSULTING",
    # science / research (PHYSICIST, ECONOMIST)
    "MATHEMATICIAN": "SCIENCE / RESEARCH",
    "PHYSICS": "SCIENCE / RESEARCH",
    "HISTORIAN": "SCIENCE / RESEARCH",
    # government / military (POLICE DETECTIVE, LOBBYIST, CONGRESSIONAL
    # CANDIDATE, COURT RECEIVER, GOV'T RELATIONS)
    "POLICE OFFICER": "GOVERNMENT / MILITARY",
    "CAPTAIN, COP UNIT": "GOVERNMENT / MILITARY",
    "CITY CLERK": "GOVERNMENT / MILITARY",
    "BUILDING OFFICIAL": "GOVERNMENT / MILITARY",
    "CENSUS FIELD REPRESENTATIVE": "GOVERNMENT / MILITARY",
    "COURT COORDINATOR": "GOVERNMENT / MILITARY",
    "SR HEARING EXAMINER": "GOVERNMENT / MILITARY",
    "MEMBER, AG. LABOR RELATIONS BD": "GOVERNMENT / MILITARY",
    "LOBBYING": "GOVERNMENT / MILITARY",
    "CONGRESSIONAL AFFAIRS": "GOVERNMENT / MILITARY",
    "CANDIDATE": "GOVERNMENT / MILITARY",
    "OHIO HOUSE CANDIDATE, DISTRICT 4": "GOVERNMENT / MILITARY",
    "OFFICE HOLDER/CANDIDATE FOR TEXAS HD 8": "GOVERNMENT / MILITARY",
    # legal (JUDGE, ARBITRATOR, FIDUCIARY)
    "ALJ": "LEGAL",
    "ALTERNATIVE DISPUTE RESOLUTION SERVICE": "LEGAL",
    "PRIVATE PROFESSIONAL FIDUCIARY": "LEGAL",
    # construction / trades (DESIGN AND BUILD, REMODELER, MECHANIC)
    "HANDYMAN": "CONSTRUCTION / TRADES",
    "MILLWORK": "CONSTRUCTION / TRADES",
    "GENERAL CONTRACTING": "CONSTRUCTION / TRADES",
    "DESIGN/BUILD": "CONSTRUCTION / TRADES",
    "CABINETS/CARPORTS": "CONSTRUCTION / TRADES",
    "WATCHMAKER": "CONSTRUCTION / TRADES",
    # transportation (MOVER, LOGISTICS; BLS SOC 53-7051 material moving)
    "FORKLIFT OPERATOR": "TRANSPORTATION",
    # food / hospitality (FOOD SERVICE, CHEF, HOTEL)
    "CHEESE MAKER": "FOOD / HOSPITALITY",
    "CULINARIAN": "FOOD / HOSPITALITY",
    "FOODSERVICE": "FOOD / HOSPITALITY",
    "FOOD TRUCK VENDOR": "FOOD / HOSPITALITY",
    "CONCIERGE": "FOOD / HOSPITALITY",
    # business (AUTOMOBILE DEALER, DISTRIBUTOR, PAPER CONVERTER, OWNER)
    "TRUCK DEALER": "BUSINESS / ENTREPRENEUR",
    "PETERBILT TRUCK DEALER": "BUSINESS / ENTREPRENEUR",
    "AUTOMOBILE DEALERSHIP": "BUSINESS / ENTREPRENEUR",
    "ESTATE DEALER": "BUSINESS / ENTREPRENEUR",
    "SUPERMARKET": "BUSINESS / ENTREPRENEUR",
    "PRODUCE DISTRIBUTION": "BUSINESS / ENTREPRENEUR",
    "SOLE SHAREHOLDER": "BUSINESS / ENTREPRENEUR",
    "PRINTER": "BUSINESS / ENTREPRENEUR",
    # finance (LENDING, PAYMENTS PROFESSIONAL, BANKER, PRIVATE EQUITY)
    "LOANS": "FINANCE / INVESTMENT",
    "CREDIT RATINGS": "FINANCE / INVESTMENT",
    "DEBT ACQUISITION": "FINANCE / INVESTMENT",
    "PAYMENT PROCESSING": "FINANCE / INVESTMENT",
    "BANK OFFICER": "FINANCE / INVESTMENT",
    "PERE": "FINANCE / INVESTMENT",  # private equity real estate (KENNEDY WILSON)
    "STOCKS": "FINANCE / INVESTMENT",
    # insurance: INS is the INS -> INSURANCE fix; the donor files INSURANCE AGENT
    "INS AGENCY": "INSURANCE",
    # nonprofit (DEVELOPMENT, DIRECTOR OF ADVANCEMENT, JEWISH PROFESSIONAL)
    "MAJOR GIFT OFFICER": "NONPROFIT / PHILANTHROPY",
    "DEVELOPMENT OFFICER": "NONPROFIT / PHILANTHROPY",
    "INSTITUTIONAL GIVING GRANTS": "NONPROFIT / PHILANTHROPY",
    "CHARITABLE GIVING": "NONPROFIT / PHILANTHROPY",
    "JEWISH COMMUNAL PROFESSIONAL": "NONPROFIT / PHILANTHROPY",
    # sales / marketing (GIFT BUYER, MEDIA BUYER, CUSTOMER SERVICE, RECRUITER,
    # LICENSING, PROPANE MARKETER)
    "BUYER": "SALES / MARKETING",
    "CANDY & GIFT BUYER": "SALES / MARKETING",
    # CUSTOMER SERVICE REP(RESENTATIVE) is not mapped: test_occupations_categories
    # pins the long form to OTHER (its point: not a legislator)
    "CALL CENTER AGENT": "SALES / MARKETING",
    "CLIENT SERVICE ASSOCIATE": "SALES / MARKETING",
    "RECRUITING": "SALES / MARKETING",
    "LICENSING AGENCY": "SALES / MARKETING",
    "PETROLEUM MARKETER": "SALES / MARKETING",
    "DIRECT MAIL": "SALES / MARKETING",
    # management (GENERAL MANAGER, CLERK, OFFICE STAFF); every GM filer in the
    # data is a manager, one also files GENERAL MANAGER
    "GM": "MANAGEMENT",
    "RECEPTION": "MANAGEMENT",
    "FRONT DESK": "MANAGEMENT",
    # executive: C-level titles (CLO chief legal/learning, CGO chief growth,
    # CMTO chief marketing & technology officer)
    "CLO": "EXECUTIVE / C-SUITE",
    "CGO": "EXECUTIVE / C-SUITE",
    "CMTO": "EXECUTIVE / C-SUITE",
    # agriculture (FARM, RANCH)
    "HORTICULTURIST": "AGRICULTURE",
    "FERTILIZER": "AGRICULTURE",
    # FEC's 38-character cut, kept as filed because the donor never files the
    # full text and the web does not show it: ADVIS... is CONSULTING whichever
    # way it ends; OPERATI... gets what OPERATIONS (the MANAGEMENT rule) gets
    "INFRASTRUCTURE DEVELOPMENT AND OPERATI": "MANAGEMENT",
    "INSTITUTIONAL & STRATEGIC GROWTH ADVIS": "CONSULTING",
}
