"""Occupation category regex rules — ORDER MATTERS, first match wins."""
import re

CATEGORY_RULES = [
    # status categories override profession
    ('RETIRED', r'^RETIRED$'),
    ('NOT EMPLOYED', r'^NOT EMPLOYED$'),
    ('STUDENT', r'^STUDENT$'),
    ('HOMEMAKER', r'^HOMEMAKER$|^HOUSEWIFE$|^STAY.AT.HOME|^MOM$|^SAHM$'),
    ('SELF-EMPLOYED', r'^SELF-EMPLOYED$'),

    # Public-office titles. They come before the professional rules because
    # words inside them would otherwise win: SECRETARY (MANAGEMENT) in DEPUTY
    # SECRETARY OF DEFENSE, PRESIDENT/CHIEF (EXECUTIVE), ADVISOR (CONSULTING).
    # Bare AMBASSADOR and REPRESENTATIVE are left out on purpose: in the FEC
    # data they are also brand ambassadors and sales/field representatives.
    ('GOVERNMENT / MILITARY',
     r'\bU\.?S\.? (?:SENATOR|REPRESENTATIVE|AMBASSADOR'
     r'|CONGRESS(?:MAN|WOMAN|MEMBER))\b'
     r'|\bSTATE (?:SENATOR|REPRESENTATIVE|ASSEMBLY(?:MAN|WOMAN|MEMBER))\b'
     r'|\bSENATOR\b|\bLEGISLATOR\b|\bCONGRESS(?:MAN|WOMAN)\b'
     r'|^AMBASSADOR TO\b|\bSPECIAL ENVOY\b'
     r'|\bSECRETARY OF (?:DEFENSE|STATE|HOMELAND SECURITY|COMMERCE|ENERGY'
     r'|LABOR|AGRICULTURE|TRANSPORTATION|VETERANS AFFAIRS'
     r'|THE (?:ARMY|NAVY|AIR FORCE|TREASURY|INTERIOR))\b'),

    # News journalists: the category the JOURNALIST fix already uses. Before
    # EXECUTIVE so "ANCHOR AND CHIEF ... CORRESPONDENT" is not a C-suite
    # title (CHIEF). CORRESPONDENT BANKING is a finance term, not a reporter.
    ('ARTS / ENTERTAINMENT',
     r'\bJOURNALIST\b|\bCORRESPONDENT\b(?! BANK)'
     r'|^ANCHOR(?: AND\b|$)|\bNEWS ANCHOR\b|\bANCHOR(?:MAN|WOMAN)\b'),

    # A COUNSELOR is not a lawyer. School, college, career and guidance
    # counselors are education (BLS SOC 21-1012); clinical, mental-health,
    # licensed professional, genetic and addiction counselors are health care.
    # LICENSED ... COUNSEL also catches FEC's 38-character truncation of
    # LICENSED PROFESSIONAL CLINICAL COUNSELOR. A bare COUNSELOR is ambiguous
    # (counselor-at-law vs therapist vs camp counselor) and stays OTHER.
    ('EDUCATION',
     r'\b(?:SCHOOL|COLLEGE|CAREER|GUIDANCE|ADMISSIONS?|ACADEMIC) COUNSELOR\b'),
    ('MEDICAL / HEALTHCARE',
     r'\b(?:CLINICAL|MENTAL HEALTH|BEHAVIORAL|PROFESSIONAL|GENETIC|ADDICTION'
     r'|SUBSTANCE ABUSE|REHABILITATION|GRIEF|TRAUMA|MARRIAGE|FAMILY)'
     r' COUNSELOR\b'
     r'|\bLICENSED\b.*\bCOUNSEL'),

    # professional categories — more specific before broader
    ('LEGAL',
     r'ATTORNEY|LAWYER|JUDGE|PARALEGAL|LEGAL|\bCOUNSEL\b|\bCOUNSELL?OR AT LAW\b'
     r'|SOLICITOR|JURIS'
     r'|ESQUIRE|\bESQ\b|ARBITRATOR|MEDIATOR|LAW CLERK'),

    ('MEDICAL / HEALTHCARE',
     # physicians and specialists
     r'PHYSICIAN|DOCTOR|SURGEON|DENTIST|DENTAL|NURSE|PHARMACIST|PSYCHOLOGIST'
     r'|THERAPIST|MEDICAL|HEALTHCARE|HOSPITAL|EMT|PARAMEDIC'
     r'|RADIOLOG|PEDIATRIC|OPHTHALMOLOG|ANESTHESIOLOG|PODIATRI'
     r'|ORTHODONTI|PERIODONTI|DERMATOLOG|VETERINAR|UROLOG|CARDIOLOG'
     r'|ENDODONTI|OPTOMETRI|PSYCHIATRI|NEUROLOG|ONCOLOG|PATHOLOG'
     r'|RHEUMATOLOG|GASTROENTEROLOG|PULMONOLOG|HEMATOLOG|GYNECOLOG|OB.?GYN'
     r'|OBSTETRICI|NEONATOLOG|GERIATRIC|PALLIATIVE|PSYCHOANALYS'
     # allied health
     r'|SOCIAL WORK|CLINICAL SOCIAL|HEALTH CARE|HOME CARE|HEALTH COACH'
     r'|BEHAVIOR ANALYS|SPEECH PATHOLOG|SPEECH LANGUAGE'
     r'|PHYSICAL THERAP|OCCUPATIONAL THERAP'
     r'|PROVIDER|PRACTITIONER'),

    ('FINANCE / INVESTMENT',
     # INVEST but not INVESTIGATOR / INVESTIGATION / INVESTIGATIVE
     r'FINANCE|FINANCIAL|INVEST(?!IGAT)\w*|BANKER|BANKING|PORTFOLIO'
     r'|PRIVATE EQUITY|VENTURE CAPITAL|SECURITIES|TRADER|BROKER|TREASURER'
     r'|TRADING|WEALTH MANAG|TRUST ADMIN|TRUST ADMINISTRATION'
     r'|CREDIT ANALYS|COMMODITIES|LENDING|\bLENDER\b|FIXED INCOME'
     r'|FAMILY OFFICE|INV MGR|ACTUAR|\bANALYST\b'),

    ('REAL ESTATE',
     r'REAL ESTATE|PROPERTY|REALTY|REALTOR|LANDLORD|REAL ESTSTE'
     r'|REAL EATATE|REAL RSTATE|HOUSING DEVELOP|MORTGAGE LOAN'
     r'|LAND DEVELOPER|HOME DEVELOPER|HOTEL DEVELOPER|R/E DEVELOP'
     r'|\bBUILDER/DEVELOPER\b|\bBUILDER DEVELOPER\b'),

    ('EXECUTIVE / C-SUITE',
     # whole-word C-titles: bare CEO/COO/CTO/CIO also sit inside INSTRUCTOR,
     # COORDINATOR, CONTRACTOR, SOCIOLOGY, PRECIOUS, COOKING ...
     r'\b(?:CEO|COO|CTO|CIO|CMO|CDO|CFO)\b|\bCHROO?\b|EXECUTIVE|PRESIDENT|\bCHAIR(?:MAN|WOMAN|PERSON)?\b'
     r'|VICE PRESIDENT|DIRECTOR|PARTNER|FOUNDER|CHIEF'
     r'|PRINCIPAL|\bSENIOR VP\b|\bCO-CHAIRMAN\b|CHAIRMAN EMERITUS'
     r'|MANAGING MEMBER|MANAGING DIRECTOR|MANAGING PARTNER'
     r'|HEAD OF|BOARD MEMBER|COMMISSIONER'),

    ('BUSINESS / ENTREPRENEUR',
     r'BUSINESS OWNER|ENTREPRENEUR|\bOWNER\b|BUSINESS|SMALL BUSINESS|FRANCHISE'
     r'|MERCHANT|MANUFACTURER|MANUFACTURING|\bWHOLESAL|\bRETAIL\b'
     r'|AUTO DEALER|CAR DEALER|AUTOMOTIVE DEALER|AUTOMOTIVE'
     r'|IMPORT.?EXPORT|JEWEL|RECYCLING|SCRAP METAL|E-COMMERCE'
     r'|HANDBAG|DISTRIBUTOR'),

    ('TECHNOLOGY',
     r'SOFTWARE|ENGINEER|PROGRAMMER|DEVELOPER|TECHNOLOGY|TECH'
     r'|\bIT\b|DATA SCIEN|DATA ANALY|COMPUTER|CYBER|NETWORK'
     r'|SYSTEM|DEVOPS|CLOUD|\bUX\b|\bUI\b|WIRELESS|INVENTOR'),

    ('ACCOUNTING / TAX',
     r'\bCPA\b|ACCOUNTANT|ACCOUNTING|\bTAX\b|AUDITOR|BOOKKEEPER'
     r'|CONTROLLER|COMPTROLLER'),

    ('EDUCATION',
     r'TEACHER|PROFESSOR|EDUCATOR|INSTRUCTOR|TUTOR|LIBRARIAN'
     r'|SCHOOL|UNIVERSITY|COLLEGE|FACULTY|LECTURER|ACADEMIC'
     r'|EDUCATIONAL SPECIALIST|HIGHER EDUCATION|\bINTERN\b'),

    ('CONSULTING',
     r'CONSULTANT|CONSULTING|ADVISOR|ADVISORY|ADVISER|STRATEGIST'),

    ('SALES / MARKETING',
     r'SALES|MARKETING|ADVERTISING|PUBLIC RELATION'
     r'|\bBRAND\b|MEDIA|COMMUNICATIONS|PUBLICIST'
     r'|TRAVEL AGENT|RECRUITER|TALENT AGENT|FUNDRAIS'
     r'|PLANNED GIVING|CORPORATE OUTREACH|CORPORATE RELATIONS'
     r'|CUSTOMER SUCCESS|MARKET RESEARCH'),

    ('INSURANCE',
     r'INSURANCE'),

    ('RELIGIOUS',
     r'RABBI|PASTOR|CLERGY|MINISTER|PRIEST|IMAM|CHAPLAIN|CHURCH|CANTOR'),

    ('GOVERNMENT / MILITARY',
     r'GOVERNMENT|MILITARY|ARMY|NAVY|AIR FORCE|FEDERAL'
     r'|STATE EMPLOY|CITY EMPLOY|POLITICAL|POLITICIAN|LOBBYIST|POLICY'
     # INVESTIGATOR only with a public employer in the title: a bare one is
     # as often a private, insurance or university investigator (OTHER)
     r'|\b(?:POLICE|STATE|COUNTY|CITY|INSPECTOR GENERAL) INVESTIGATOR\b'
     r'|REGULATORY|COURT RECEIVER'),

    ('ARTS / ENTERTAINMENT',
     # whole-word ACTOR: the bare letters sit inside CONTRACTOR and FACTORS
     r'ARTIST|WRITER|AUTHOR|MUSICIAN|\bACTOR\b|PRODUCER|DESIGNER'
     r'|PHOTOGRAPHER|ENTERTAINMENT|FILMMAKER|PUBLISHER|PUBLISHING'
     r'|EDITOR|EVENT PLANNER|EVENT PRODUCTION|OPERA SINGER'
     r'|INTERIOR DESIGN|INTERIOR ARCHITECT|CREATIVE|FASHION'
     r'|BEAUTY|SPORTS|PHOTOGRAPHY|\bDJ\b|ARCHITECTURE|\bARCHITECT\b'),

    ('SCIENCE / RESEARCH',
     r'SCIENTIST|RESEARCHER|CHEMIST|PHYSICIST|BIOLOGIST'
     r'|ECONOMIST|LABORATORY|GEOLOGIST|HYDROGEOLOG|ARCHAEOLOG'
     r'|\bSCIENCE\b'),

    ('MANAGEMENT',
     r'MANAGER|MANAGEMENT|SUPERVISOR|ADMINISTRATOR|OPERATIONS'
     r'|ADMIN|ADMINISTRATION|SECRETARY|ORGANIZER|OFFICE ADMIN'
     r'|\bASSISTANT\b|ASSOCIATE STAFF'),

    ('CONSTRUCTION / TRADES',
     r'CONSTRUCT|CONTRACTOR|PLUMB|ELECTRICIAN|CARPENTER'
     r'|HVAC|ROOFING|WELDING|MECHANIC|BUILDER|MAINTENANCE'),

    ('AGRICULTURE',
     r'FARM|RANCH|AGRICULTURE|AGRI'),

    ('TRANSPORTATION',
     r'PILOT|DRIV\w+|TRUCKING|SHIPPING|LOGISTICS|TRANSPORT|AVIATION|MOVER'),

    ('FOOD / HOSPITALITY',
     r'CHEF|COOK|RESTAURANT|HOTEL|BAKERY|CATER|SERVER'
     r'|WAITER|HOSPITALITY|FOOD SERVICE|BARISTA'),

    ('NONPROFIT / PHILANTHROPY',
     r'VOLUNTEER|PHILANTHROPIST|NONPROFIT|NON-PROFIT|NON PROFIT'
     r'|FOUNDATION|CHARITY|NGO|PHILANTHROPY|SOCIAL ACTIVIST'),

]

# pre-compiled for performance
CATEGORY_PATTERNS = [(cat, re.compile(pat)) for cat, pat in CATEGORY_RULES]

VALID_CATEGORIES = frozenset(
    [cat for cat, _ in CATEGORY_RULES]
    + [
        'OTHER',
        'POLITICAL COMMITTEE', 'CONGRESSIONAL CAMPAIGN',
        'SENATE CAMPAIGN', 'POLITICAL ACTION COMMITTEE',
        'PARTY ORGANIZATION',
        # written by the entity classifier (not CATEGORY_RULES) for
        # ORGANIZATION entities — the gate must list it or every run
        # reports it as invalid
        'ORGANIZATION',
    ]
)


# Broader second-pass rules for values that remained OTHER.
RECLASSIFY_CATEGORY_RULES = [
    (r'\bATTORNEY\b|\bLAWYER\b|\bLEGAL\b|\bCOUNSEL\b|\bESQ\b', 'LEGAL'),
    (r'\bDOCTOR\b|\bPHYSICIAN\b|\bSURGEON\b|\bMD\b|\bDENTIST\b|\bNURSE\b|\bRN\b|\bPHARMACIST\b|\bVETERINAR', 'MEDICAL / HEALTHCARE'),
    (r'\bENGINEER\b|\bSOFTWARE\b|\bDEVELOPER\b|\bPROGRAMMER\b|\bIT\b|\bTECH\b', 'TECHNOLOGY'),
    (r'\bPROFESSOR\b|\bTEACHER\b|\bEDUCATOR\b|\bPRINCIPAL\b|\bDEAN\b|\bACADEMIC\b', 'EDUCATION'),
    (r'\bREAL ESTATE\b|\bREALTOR\b|\bBROKER\b|\bPROPERT', 'REAL ESTATE'),
    (r'\bACCOUNTANT\b|\bCPA\b|\bAUDITOR\b|\bBOOKKEEPER\b', 'FINANCE / INVESTMENT'),
    (r'\bBANKER\b|\bINVEST\b|\bFINANC\b|\bTRADER\b|\bANALYST\b|\bHEDGE\b|\bPORTFOLIO\b', 'FINANCE / INVESTMENT'),
    (r'\bCONSULTANT\b|\bADVISOR\b', 'CONSULTING'),
    (r'\bRABBI\b|\bPASTOR\b|\bMINISTER\b|\bCLERGY\b|\bPRIEST\b', 'RELIGIOUS'),
    (r'\bWRITER\b|\bAUTHOR\b|\bJOURNALIST\b|\bEDITOR\b|\bREPORTER\b|\bPUBLISH', 'ARTS / ENTERTAINMENT'),
    (r'\bARCHITECT\b', 'ARTS / ENTERTAINMENT'),
    # COUNSELOR is decided by its qualifier in CATEGORY_RULES (school vs
    # clinical); a bare or unknown-kind COUNSELOR stays OTHER
    (r'\bPSYCHOLOG\b|\bTHERAPIST\b|\bSOCIAL WORK\b', 'MEDICAL / HEALTHCARE'),
    (r'\bSALES\b|\bMARKETING\b|\bADVERTIS', 'SALES / MARKETING'),
    # bare VP / SVP / EVP titles (VP OF STRATEGY, CLINICAL DEVELOPMENT SVP):
    # the first pass only knows VICE PRESIDENT and SENIOR VP
    (r'\bEXECUTIVE\b|\bCEO\b|\bCFO\b|\bCOO\b|\bPRESIDENT\b|\bDIRECTOR\b'
     r'|\bS?VP\b|\bEVP\b', 'EXECUTIVE / C-SUITE'),
    (r'\bPILOT\b|\bAVIAT', 'TRANSPORTATION'),
    (r'\bPHILANTHROP\b|\bNON.?PROFIT\b|\bNGO\b', 'NONPROFIT / PHILANTHROPY'),
]
