"""Occupation category regex rules — ORDER MATTERS, first match wins."""
import re

CATEGORY_RULES = [
    # status categories override profession
    ('RETIRED', r'^RETIRED$'),
    ('NOT EMPLOYED', r'^NOT EMPLOYED$'),
    ('STUDENT', r'^STUDENT$'),
    ('HOMEMAKER', r'^HOMEMAKER$|^HOUSEWIFE$|^STAY.AT.HOME|^MOM$|^SAHM$'),
    ('SELF-EMPLOYED', r'^SELF-EMPLOYED$'),

    # Public-office titles. They come before the professional rules because
    # words inside them would otherwise win: SECRETARY (MANAGEMENT) in DEPUTY
    # SECRETARY OF DEFENSE, PRESIDENT/CHIEF (EXECUTIVE), ADVISOR (CONSULTING).
    # Bare AMBASSADOR and REPRESENTATIVE are left out on purpose: in the FEC
    # data they are also brand ambassadors and sales/field representatives.
    ('GOVERNMENT / MILITARY',
     r'\bU\.?S\.? (?:SENATOR|REPRESENTATIVE|AMBASSADOR'
     r'|CONGRESS(?:MAN|WOMAN|MEMBER))\b'
     r'|\bSTATE (?:SENATOR|REPRESENTATIVE|ASSEMBLY(?:MAN|WOMAN|MEMBER))\b'
     r'|\bSENATOR\b|\bLEGISLATOR\b|\bCONGRESS(?:MAN|WOMAN)\b'
     r'|^AMBASSADOR TO\b|\bSPECIAL ENVOY\b'
     r'|\bSECRETARY OF (?:DEFENSE|STATE|HOMELAND SECURITY|COMMERCE|ENERGY'
     r'|LABOR|AGRICULTURE|TRANSPORTATION|VETERANS AFFAIRS'
     r'|THE (?:ARMY|NAVY|AIR FORCE|TREASURY|INTERIOR))\b'),

    # News journalists: the category the JOURNALIST fix already uses. Before
    # EXECUTIVE so "ANCHOR AND CHIEF ... CORRESPONDENT" is not a C-suite
    # title (CHIEF). CORRESPONDENT BANKING is a finance term, not a reporter.
    ('ARTS / ENTERTAINMENT',
     r'\bJOURNALIST\b|\bCORRESPONDENT\b(?! BANK)'
     r'|^ANCHOR(?: AND\b|$)|\bNEWS ANCHOR\b|\bANCHOR(?:MAN|WOMAN)\b'),

    # A COUNSELOR is not a lawyer. School, college, career and guidance
    # counselors are education (BLS SOC 21-1012); clinical, mental-health,
    # licensed professional, genetic and addiction counselors are health care.
    # LICENSED ... COUNSEL also catches FEC's 38-character truncation of
    # LICENSED PROFESSIONAL CLINICAL COUNSELOR. A bare COUNSELOR is ambiguous
    # (counselor-at-law vs therapist vs camp counselor) and stays OTHER.
    ('EDUCATION',
     r'\b(?:SCHOOL|COLLEGE|CAREER|GUIDANCE|ADMISSIONS?|ACADEMIC) COUNSELOR\b'),
    ('MEDICAL / HEALTHCARE',
     r'\b(?:CLINICAL|MENTAL HEALTH|BEHAVIORAL|PROFESSIONAL|GENETIC|ADDICTION'
     r'|SUBSTANCE ABUSE|REHABILITATION|GRIEF|TRAUMA|MARRIAGE|FAMILY)'
     r' COUNSELOR\b'
     r'|\bLICENSED\b.*\bCOUNSEL'),

    # professional categories — more specific before broader
    ('LEGAL',
     r'ATTORNEY|LAWYER|JUDGE|PARALEGAL|LEGAL|\bCOUNSEL\b|\bCOUNSELL?OR AT LAW\b'
     r'|SOLICITOR|JURIS'
     r'|ESQUIRE|\bESQ\b|ARBITRATOR|MEDIATOR|LAW CLERK'),

    ('MEDICAL / HEALTHCARE',
     # physicians and specialists
     r'PHYSICIAN|DOCTOR|SURGEON|DENTIST|DENTAL|NURSE|PHARMACIST|PSYCHOLOGIST'
     r'|THERAPIST|MEDICAL|HEALTHCARE|HOSPITAL|EMT|PARAMEDIC'
     r'|RADIOLOG|PEDIATRIC|OPHTHALMOLOG|ANESTHESIOLOG|PODIATRI'
     r'|ORTHODONTI|PERIODONTI|DERMATOLOG|VETERINAR|UROLOG|CARDIOLOG'
     r'|ENDODONTI|OPTOMETRI|PSYCHIATRI|NEUROLOG|ONCOLOG|PATHOLOG'
     r'|RHEUMATOLOG|GASTROENTEROLOG|PULMONOLOG|HEMATOLOG|GYNECOLOG|OB.?GYN'
     r'|OBSTETRICI|NEONATOLOG|GERIATRIC|PALLIATIVE|PSYCHOANALYS'
     # allied health
     r'|SOCIAL WORK|CLINICAL SOCIAL|HEALTH CARE|HOME CARE|HEALTH COACH'
     r'|BEHAVIOR ANALYS|SPEECH PATHOLOG|SPEECH LANGUAGE'
     r'|PHYSICAL THERAP|OCCUPATIONAL THERAP'
     r'|PROVIDER|PRACTITIONER'),

    ('FINANCE / INVESTMENT',
     # INVEST but not INVESTIGATOR / INVESTIGATION / INVESTIGATIVE
     r'FINANCE|FINANCIAL|INVEST(?!IGAT)\w*|BANKER|BANKING|PORTFOLIO'
     r'|PRIVATE EQUITY|VENTURE CAPITAL|SECURITIES|TRADER|BROKER|TREASURER'
     r'|TRADING|WEALTH MANAG|TRUST ADMIN|TRUST ADMINISTRATION'
     r'|CREDIT ANALYS|COMMODITIES|LENDING|\bLENDER\b|FIXED INCOME'
     r'|FAMILY OFFICE|INV MGR|ACTUAR|\bANALYST\b'),

    ('REAL ESTATE',
     r'REAL ESTATE|PROPERTY|REALTY|REALTOR|LANDLORD|REAL ESTSTE'
     r'|REAL EATATE|REAL RSTATE|HOUSING DEVELOP|MORTGAGE LOAN'
     r'|LAND DEVELOPER|HOME DEVELOPER|HOTEL DEVELOPER|R/E DEVELOP'
     r'|\bBUILDER/DEVELOPER\b|\bBUILDER DEVELOPER\b'),

    ('EXECUTIVE / C-SUITE',
     # whole-word C-titles: bare CEO/COO/CTO/CIO also sit inside INSTRUCTOR,
     # COORDINATOR, CONTRACTOR, SOCIOLOGY, PRECIOUS, COOKING ...
     r'\b(?:CEO|COO|CTO|CIO|CMO|CDO|CFO)\b|\bCHROO?\b|EXECUTIVE|PRESIDENT|\bCHAIR(?:MAN|WOMAN|PERSON)?\b'
     r'|VICE PRESIDENT|DIRECTOR|PARTNER|FOUNDER|CHIEF'
     r'|PRINCIPAL|\bSENIOR VP\b|\bCO-CHAIRMAN\b|CHAIRMAN EMERITUS'
     r'|MANAGING MEMBER|MANAGING DIRECTOR|MANAGING PARTNER'
     r'|HEAD OF|BOARD MEMBER|COMMISSIONER'),

    ('BUSINESS / ENTREPRENEUR',
     r'BUSINESS OWNER|ENTREPRENEUR|\bOWNER\b|BUSINESS|SMALL BUSINESS|FRANCHISE'
     r'|MERCHANT|MANUFACTURER|MANUFACTURING|\bWHOLESAL|\bRETAIL\b'
     r'|AUTO DEALER|CAR DEALER|AUTOMOTIVE DEALER|AUTOMOTIVE'
     r'|IMPORT.?EXPORT|JEWEL|RECYCLING|SCRAP METAL|E-COMMERCE'
     r'|HANDBAG|DISTRIBUTOR'),

    ('TECHNOLOGY',
     r'SOFTWARE|ENGINEER|PROGRAMMER|DEVELOPER|TECHNOLOGY|TECH'
     r'|\bIT\b|DATA SCIEN|DATA ANALY|COMPUTER|CYBER|NETWORK'
     r'|SYSTEM|DEVOPS|CLOUD|\bUX\b|\bUI\b|WIRELESS|INVENTOR'),

    ('ACCOUNTING / TAX',
     r'\bCPA\b|ACCOUNTANT|ACCOUNTING|\bTAX\b|AUDITOR|BOOKKEEPER'
     r'|CONTROLLER|COMPTROLLER'),

    ('EDUCATION',
     r'TEACHER|PROFESSOR|EDUCATOR|INSTRUCTOR|TUTOR|LIBRARIAN'
     r'|SCHOOL|UNIVERSITY|COLLEGE|FACULTY|LECTURER|ACADEMIC'
     r'|EDUCATIONAL SPECIALIST|HIGHER EDUCATION|\bINTERN\b'),

    ('CONSULTING',
     r'CONSULTANT|CONSULTING|ADVISOR|ADVISORY|ADVISER|STRATEGIST'),

    ('SALES / MARKETING',
     r'SALES|MARKETING|ADVERTISING|PUBLIC RELATION'
     r'|\bBRAND\b|MEDIA|COMMUNICATIONS|PUBLICIST'
     r'|TRAVEL AGENT|RECRUITER|TALENT AGENT|FUNDRAIS'
     r'|PLANNED GIVING|CORPORATE OUTREACH|CORPORATE RELATIONS'
     r'|CUSTOMER SUCCESS|MARKET RESEARCH'),

    ('INSURANCE',
     r'INSURANCE'),

    ('RELIGIOUS',
     r'RABBI|PASTOR|CLERGY|MINISTER|PRIEST|IMAM|CHAPLAIN|CHURCH|CANTOR'),

    ('GOVERNMENT / MILITARY',
     r'GOVERNMENT|MILITARY|ARMY|NAVY|AIR FORCE|FEDERAL'
     r'|STATE EMPLOY|CITY EMPLOY|POLITICAL|POLITICIAN|LOBBYIST|POLICY'
     # INVESTIGATOR only with a public employer in the title: a bare one is
     # as often a private, insurance or university investigator (OTHER)
     r'|\b(?:POLICE|STATE|COUNTY|CITY|INSPECTOR GENERAL) INVESTIGATOR\b'
     r'|REGULATORY|COURT RECEIVER'),

    ('ARTS / ENTERTAINMENT',
     # whole-word ACTOR: the bare letters sit inside CONTRACTOR and FACTORS
     r'ARTIST|WRITER|AUTHOR|MUSICIAN|\bACTOR\b|PRODUCER|DESIGNER'
     r'|PHOTOGRAPHER|ENTERTAINMENT|FILMMAKER|PUBLISHER|PUBLISHING'
     r'|EDITOR|EVENT PLANNER|EVENT PRODUCTION|OPERA SINGER'
     r'|INTERIOR DESIGN|INTERIOR ARCHITECT|CREATIVE|FASHION'
     r'|BEAUTY|SPORTS|PHOTOGRAPHY|\bDJ\b|ARCHITECTURE|\bARCHITECT\b'),

    ('SCIENCE / RESEARCH',
     r'SCIENTIST|RESEARCHER|CHEMIST|PHYSICIST|BIOLOGIST'
     r'|ECONOMIST|LABORATORY|GEOLOGIST|HYDROGEOLOG|ARCHAEOLOG'
     r'|\bSCIENCE\b'),

    ('MANAGEMENT',
     r'MANAGER|MANAGEMENT|SUPERVISOR|ADMINISTRATOR|OPERATIONS'
     r'|ADMIN|ADMINISTRATION|SECRETARY|ORGANIZER|OFFICE ADMIN'
     r'|\bASSISTANT\b|ASSOCIATE STAFF'),

    ('CONSTRUCTION / TRADES',
     r'CONSTRUCT|CONTRACTOR|PLUMB|ELECTRICIAN|CARPENTER'
     r'|HVAC|ROOFING|WELDING|MECHANIC|BUILDER|MAINTENANCE'),

    ('AGRICULTURE',
     r'FARM|RANCH|AGRICULTURE|AGRI'),

    ('TRANSPORTATION',
     r'PILOT|DRIV\w+|TRUCKING|SHIPPING|LOGISTICS|TRANSPORT|AVIATION|MOVER'),

    ('FOOD / HOSPITALITY',
     r'CHEF|COOK|RESTAURANT|HOTEL|BAKERY|CATER|SERVER'
     r'|WAITER|HOSPITALITY|FOOD SERVICE|BARISTA'),

    ('NONPROFIT / PHILANTHROPY',
     r'VOLUNTEER|PHILANTHROPIST|NONPROFIT|NON-PROFIT|NON PROFIT'
     r'|FOUNDATION|CHARITY|NGO|PHILANTHROPY|SOCIAL ACTIVIST'),

]

# pre-compiled for performance
CATEGORY_PATTERNS = [(cat, re.compile(pat)) for cat, pat in CATEGORY_RULES]

VALID_CATEGORIES = frozenset(
    [cat for cat, _ in CATEGORY_RULES]
    + [
        'OTHER',
        'POLITICAL COMMITTEE', 'CONGRESSIONAL CAMPAIGN',
        'SENATE CAMPAIGN', 'POLITICAL ACTION COMMITTEE',
        'PARTY ORGANIZATION',
        # written by the entity classifier (not CATEGORY_RULES) for
        # ORGANIZATION entities — the gate must list it or every run
        # reports it as invalid
        'ORGANIZATION',
    ]
)


# Explicit overrides for occupations the regex rules misclassify.
CATEGORY_OVERRIDES = {
    # technology; bare "DEVELOPER" in FEC data is usually software
    "SOFTWARE DEVELOPER": "TECHNOLOGY",
    "SOFTWARE EXECUTIVE": "TECHNOLOGY",
    "SOFTWARE RELEASE ANALYST": "TECHNOLOGY",
    "SOFTWARE DEVELOPMENT MANAGER": "TECHNOLOGY",
    "QUANT DEVELOPER": "TECHNOLOGY",
    "DEVELOPER": "TECHNOLOGY",
    "DEVELOPER/DESIGNER": "TECHNOLOGY",
    "DATABASE DEVELOPER": "TECHNOLOGY",
    "DATABASE ANALYTICS": "TECHNOLOGY",

    # construction / trades; CONTRACTOR is caught by the EXECUTIVE regex
    "CONTRACTOR": "CONSTRUCTION / TRADES",
    "GENERAL CONTRACTOR": "CONSTRUCTION / TRADES",
    "ELECTRICAL CONTRACTOR": "CONSTRUCTION / TRADES",
    "ROOFING CONTRACTOR": "CONSTRUCTION / TRADES",
    "FLOORING CONTRACTOR": "CONSTRUCTION / TRADES",
    "FLOORING": "CONSTRUCTION / TRADES",
    "ARCHITECT": "CONSTRUCTION / TRADES",
    "INTERIOR ARCHITECT": "CONSTRUCTION / TRADES",

    # CHIROPRACTOR also caught by the EXECUTIVE regex
    "CHIROPRACTOR": "MEDICAL / HEALTHCARE",

    # Titles that only reached EXECUTIVE / C-SUITE through CEO/CDO/CTO/CIO
    # letters inside another word, before those were made whole-word.
    # INDEPENDENT CONTRACTOR is a work arrangement like FREELANCER, not a
    # trade; the PRIVATE MUSIC one teaches music for a park district.
    "INDEPENDENT CONTRACTOR": "SELF-EMPLOYED",
    "INDEPENDENT CONTRACTOR- PRIVATE MUSIC": "ARTS / ENTERTAINMENT",
    "VOICEOVER/AUDO PRODUCTION": "ARTS / ENTERTAINMENT",
    # AWS job code: Data Center Engineering Operations technician, level IV
    "DCEO EOT IV": "TECHNOLOGY",
    # virtual Chief Information Officer: a real C-level title, kept
    "VCIO": "EXECUTIVE / C-SUITE",
    "NURSING COORDINATOR": "MEDICAL / HEALTHCARE",
    "CLINICAL NURSING COORDINATOR": "MEDICAL / HEALTHCARE",
    # same bucket as CUSTOMER SERVICE / CUSTOMER SUCCESS and RECRUITER
    "CUSTOMER ENGAGEMENT COORDINATOR": "SALES / MARKETING",
    "RECRUITING COORDINATOR": "SALES / MARKETING",

    # finance
    "PRIVATE WEALTH ADVISOR": "FINANCE / INVESTMENT",
    "FUND MANAGER": "FINANCE / INVESTMENT",
    "MONEY MANAGEMENT": "FINANCE / INVESTMENT",
    "MONEY MANAGER": "FINANCE / INVESTMENT",
    "ECONOMIST": "FINANCE / INVESTMENT",
    "CFP": "FINANCE / INVESTMENT",

    # sales / marketing
    "BUSINESS DEVELOPMENT MANAGER": "SALES / MARKETING",
    "BUSINESS DEVELOPMENT": "SALES / MARKETING",
    "HEAD OF BUSINESS DEVELOPMENT": "SALES / MARKETING",
    "ACCOUNT EXECUTIVE": "SALES / MARKETING",

    # management
    "HUMAN RESOURCES": "MANAGEMENT",
    "CONSTRUCTION MANAGER": "MANAGEMENT",

    # executive
    "VP OF MARKETING": "EXECUTIVE / C-SUITE",
    "CHIEF DEVELOPMENT OFFICER": "EXECUTIVE / C-SUITE",

    # legal; MEDIATION contains MEDIA so the SALES/MARKETING regex fires
    "MEDIATION": "LEGAL",
    "MEDIATOR": "LEGAL",
    "FAMILY MEDIATION": "LEGAL",
    "FAMILY MEDIATOR": "LEGAL",

    "RESTAURATEUR": "FOOD / HOSPITALITY",
    "EDUCATION": "EDUCATION",

    # real estate development
    "OWNER/DEVELOPER": "REAL ESTATE",
    "PROPERTY DEVELOPMENT": "REAL ESTATE",
    "SOLAR DEVELOPER": "CONSTRUCTION / TRADES",
    "AFFORDABLE HOUSING DEVELOPER": "REAL ESTATE",

    # medical, missed by regex
    "NEPHROLOGIST": "MEDICAL / HEALTHCARE",
    "PHARMACY SERVICES": "MEDICAL / HEALTHCARE",
    "PHARMACY": "MEDICAL / HEALTHCARE",
    "PHARMACIST CONSULTANT": "MEDICAL / HEALTHCARE",
    "ORAL SURGEON": "MEDICAL / HEALTHCARE",
    "ALLERGIST": "MEDICAL / HEALTHCARE",
    "INTERNIST": "MEDICAL / HEALTHCARE",

    # government, missed by regex
    "COUNCILMEMBER": "GOVERNMENT / MILITARY",
    "CITY COUNCIL MEMBER": "GOVERNMENT / MILITARY",
    "COUNCIL MEMBER": "GOVERNMENT / MILITARY",
    "ELECTED OFFICIAL": "GOVERNMENT / MILITARY",
    "PUBLIC OFFICIAL": "GOVERNMENT / MILITARY",
    "MAYOR": "GOVERNMENT / MILITARY",
    "ALDERMAN": "GOVERNMENT / MILITARY",

    "PROPANE MARKETER": "SALES / MARKETING",
    "IMPORTER": "SALES / MARKETING",

    # real estate development variants
    "COMMERCIAL REAL ESTATE DEVELOPMENT": "REAL ESTATE",
    "REAL ESTATE DEVELOPMENT AND MANAGEMENT": "REAL ESTATE",
    "HOUSING DEVELOPMENT": "REAL ESTATE",
    "HOMELESS HOUSING": "REAL ESTATE",
    "COMMUNITY BUILDING": "REAL ESTATE",

    # executive typos and variants
    "CORP EXEC": "EXECUTIVE / C-SUITE",
    "EXEC VP": "EXECUTIVE / C-SUITE",
    "EXECUIVE": "EXECUTIVE / C-SUITE",
    "CORPORATE OFFICER": "EXECUTIVE / C-SUITE",
    "SENIOR ASSOCIATE": "EXECUTIVE / C-SUITE",
    "MANAGING MENBER": "EXECUTIVE / C-SUITE",
    "CORPORATE FIDUCIARY": "EXECUTIVE / C-SUITE",

    "CONSULTANCY": "CONSULTING",

    # arts / entertainment
    "ART GALLERIST": "ARTS / ENTERTAINMENT",
    "ENTERTAINER": "ARTS / ENTERTAINMENT",
    "DECORATOR": "ARTS / ENTERTAINMENT",
    "CORPORATE STORYTELLER": "ARTS / ENTERTAINMENT",
    "TOUR GUIDE": "ARTS / ENTERTAINMENT",
    "SUSTAINABLE DESIGN": "ARTS / ENTERTAINMENT",
    "MEETING PLANNER": "ARTS / ENTERTAINMENT",
    "INTERNATIONAL PARTY PLANNER": "ARTS / ENTERTAINMENT",

    # business
    "AUTOMOBILE DEALER": "BUSINESS / ENTREPRENEUR",
    "RETAILER": "BUSINESS / ENTREPRENEUR",
    "LUMBER BIZ": "BUSINESS / ENTREPRENEUR",
    "BUSIENSS": "BUSINESS / ENTREPRENEUR",
    "INTERNATIONAL COMMERCE": "BUSINESS / ENTREPRENEUR",
    "APARTMENTS": "REAL ESTATE",
    "HOMEBUILDING": "CONSTRUCTION / TRADES",

    # education
    "DEAN": "EDUCATION",
    "TEACHING": "EDUCATION",
    "STUDENT CUSTODIAN": "EDUCATION",

    # medical
    "REGISTERED DIETITIAN": "MEDICAL / HEALTHCARE",
    "HOLISTIC NUTRITIONIST": "MEDICAL / HEALTHCARE",
    "HEALTH COCH": "MEDICAL / HEALTHCARE",
    "CAREGIVER": "MEDICAL / HEALTHCARE",
    "CLINICAL DEVELOPMENT": "MEDICAL / HEALTHCARE",

    # management
    "MANAGET": "MANAGEMENT",
    "PROJECT MGR": "MANAGEMENT",
    "ACCOUNT CLERK": "MANAGEMENT",
    "OFFICE HELP": "MANAGEMENT",
    "PROP MNGMT": "MANAGEMENT",
    "RGM LEAD": "MANAGEMENT",

    "SW EGIEER": "TECHNOLOGY",
    "APP DEVELOPMENT": "TECHNOLOGY",

    # finance
    "GROWTH EQUITY": "FINANCE / INVESTMENT",
    "VENTURE CSPITALIST": "FINANCE / INVESTMENT",
    "UNDERWRITING": "FINANCE / INVESTMENT",

    "MARKETER": "SALES / MARKETING",

    # government
    "PUBLIC ADJUSTER": "GOVERNMENT / MILITARY",
    "PROGRAM SPECIALIST": "GOVERNMENT / MILITARY",
    "COMP CLAIMS REFEREE": "GOVERNMENT / MILITARY",
    "INFORMATION RESEARCH SPECIALIST": "GOVERNMENT / MILITARY",
    "JUDICIAL RECEIVER": "LEGAL",

    "FREELANCER": "SELF-EMPLOYED",
    "PET SITTER": "SELF-EMPLOYED",

    # batch 2

    # executive
    "DEPUTY MANAGING DIRECTOR": "EXECUTIVE / C-SUITE",
    "CO PRES": "EXECUTIVE / C-SUITE",
    "FOOD MFG EXEC": "EXECUTIVE / C-SUITE",
    "CH BD": "EXECUTIVE / C-SUITE",
    "EXEC RECRUITING/BD": "EXECUTIVE / C-SUITE",
    "SVP, MUSIC & CELEBRITY TALENT": "EXECUTIVE / C-SUITE",
    "FIN MGMT": "FINANCE / INVESTMENT",
    "FIN ADV": "FINANCE / INVESTMENT",
    "FINACIAL": "FINANCE / INVESTMENT",
    "PRIVATE WEALTH": "FINANCE / INVESTMENT",
    "PRIVATE CREDIT ALLOCATOR": "FINANCE / INVESTMENT",
    "RESTRUCTURING": "FINANCE / INVESTMENT",
    "AQUISITIONS": "FINANCE / INVESTMENT",
    "FUNDING": "FINANCE / INVESTMENT",

    # legal
    "ATROENEY": "LEGAL",
    "ATTOENY": "LEGAL",
    "ATT'Y": "LEGAL",
    "PROSECUTOR": "LEGAL",
    "FIDUCIARY": "LEGAL",

    # medical / science
    "NUCLEAR HYDROLOGIST": "SCIENCE / RESEARCH",
    "BIOSTATISTICIAN": "SCIENCE / RESEARCH",
    # the lead researcher on a grant or trial (NIH term); without this it
    # falls to EXECUTIVE through PRINCIPAL now that INVEST no longer claims it
    "PRINCIPAL INVESTIGATOR": "SCIENCE / RESEARCH",
    "PSYCHOMETRIST": "MEDICAL / HEALTHCARE",
    "LONG TERM CARE AND REHABILITATION FACI": "MEDICAL / HEALTHCARE",
    "SENIOR LIVING": "MEDICAL / HEALTHCARE",
    "MENTAL HEALTH": "MEDICAL / HEALTHCARE",
    "CLINICAL TRIALS": "MEDICAL / HEALTHCARE",
    "HESLTHCARE": "MEDICAL / HEALTHCARE",
    "PHYT": "MEDICAL / HEALTHCARE",

    # insurance
    "INSURANCE BROKER": "INSURANCE",
    "INSURANCE": "INSURANCE",
    "COMPLEX CLAIMS SPECIALIST": "INSURANCE",
    "ADJUSTER": "INSURANCE",

    # real estate
    "REAL ESTATE": "REAL ESTATE",
    "REAL EATSTE": "REAL ESTATE",
    "REAL ESTATE DEVELOPMENT": "REAL ESTATE",
    "CRE APPRAISER": "REAL ESTATE",
    "APPRAISER": "REAL ESTATE",
    "MARINA OPERATOR": "REAL ESTATE",
    "SELF STG MGMT & DVLPMT": "REAL ESTATE",
    "HOME IMPROVEMENT": "CONSTRUCTION / TRADES",

    # sales / marketing
    "MARKEITNG": "SALES / MARKETING",
    "BRANDING": "SALES / MARKETING",
    "BRANDED MERCH": "SALES / MARKETING",
    "MERCH AND PROMOTIONAL PRODUCTS": "SALES / MARKETING",
    "HEADHUNTER": "SALES / MARKETING",
    "CUSTOMER SERVICE": "SALES / MARKETING",
    "LOAN OFFICER": "SALES / MARKETING",
    "AUCTIONEER": "SALES / MARKETING",

    # education
    "INSTRUCTIONAL COACH": "EDUCATION",
    "LANG ARTS SPECIALIST": "EDUCATION",
    "BASKETBALL COACH": "EDUCATION",
    "GRAD STUDENT": "STUDENT",
    "SENIOR FELLOW": "EDUCATION",
    # roster title (Heritage Foundation): a think-tank fellow like SENIOR
    # FELLOW, not a lawyer (COUNSELOR) nor a company president (PRESIDENT)
    "SENIOR COUNSELOR TO THE PRESIDENT AND E.W. RICHARDSON FELLOW": "EDUCATION",

    # management
    "PRODUCT MANAGEENT": "MANAGEMENT",
    "PROGRAM ASSOCIATE": "MANAGEMENT",
    "OPS": "MANAGEMENT",
    "PACKAGE HANDLER": "MANAGEMENT",
    "CLERK": "MANAGEMENT",
    "OFFICE STAFF": "MANAGEMENT",
    "OPERATOR": "MANAGEMENT",
    "EMPLOYEE": "MANAGEMENT",
    "MANAY": "MANAGEMENT",
    "MD LATAM": "MANAGEMENT",

    # government
    "CONGRESSIONAL CANDIDATE": "GOVERNMENT / MILITARY",
    "STATE REP": "GOVERNMENT / MILITARY",
    "JP #5": "GOVERNMENT / MILITARY",
    "GOV'T RELATIONS": "GOVERNMENT / MILITARY",
    "LANDMAN": "GOVERNMENT / MILITARY",

    # arts / entertainment
    "HAIR STYLIST": "ARTS / ENTERTAINMENT",
    "FLORIST": "ARTS / ENTERTAINMENT",
    "TAILOR": "ARTS / ENTERTAINMENT",
    "VIDEO": "ARTS / ENTERTAINMENT",
    "BROADCAST PRODUCTION": "ARTS / ENTERTAINMENT",
    "FIELD PROD": "ARTS / ENTERTAINMENT",
    "PRODUCT DESIGN": "ARTS / ENTERTAINMENT",
    "MULTI FAMILY DESIGN": "ARTS / ENTERTAINMENT",
    "YOGA FITNESS": "ARTS / ENTERTAINMENT",
    "LIFE COACH": "CONSULTING",
    "MARRIAGE COACH": "CONSULTING",
    "FACILITATOR": "CONSULTING",

    # business
    "AUTO": "BUSINESS / ENTREPRENEUR",
    "AUTOMTIVE": "BUSINESS / ENTREPRENEUR",
    "IMPORT": "BUSINESS / ENTREPRENEUR",
    "SCRAP": "BUSINESS / ENTREPRENEUR",
    "PAPER CONVERTER": "BUSINESS / ENTREPRENEUR",
    "APPAREL": "BUSINESS / ENTREPRENEUR",
    "JEWLERY": "BUSINESS / ENTREPRENEUR",
    "CLEANNG SERVICE": "BUSINESS / ENTREPRENEUR",
    "ENERGY": "BUSINESS / ENTREPRENEUR",
    "POWER": "BUSINESS / ENTREPRENEUR",
    "OIL & GAS": "BUSINESS / ENTREPRENEUR",
    "DIGITAL TRANSFORMATION": "TECHNOLOGY",

    "ISRAEL TOUR OPERATOR": "FOOD / HOSPITALITY",

    # nonprofit
    "FUND-RAISING": "NONPROFIT / PHILANTHROPY",
    "JEWISH PROFESSIONAL": "NONPROFIT / PHILANTHROPY",
    "DIR OF PROGRAMMING": "NONPROFIT / PHILANTHROPY",
    "DIRECT OF CURRICULUM DEVELOPMENT": "EDUCATION",

    # science
    "MEMBER OF RESEARCH STAFF": "SCIENCE / RESEARCH",
    "PSYCHOLOGY": "SCIENCE / RESEARCH",

    # batch 3: final stragglers
    "DEVELOPMENT": "NONPROFIT / PHILANTHROPY",  # fundraising context in this data
    "INTERNATIONAL DEVELOPMENT": "NONPROFIT / PHILANTHROPY",
    "VP OF DEVELOPMENT": "NONPROFIT / PHILANTHROPY",
    "INVESTMENT MANAGEMENT": "FINANCE / INVESTMENT",
    "MANAGING PARTNER": "EXECUTIVE / C-SUITE",
    "OWNER": "BUSINESS / ENTREPRENEUR",
    "ENTREPRENEUR": "BUSINESS / ENTREPRENEUR",
    "ATTORNEY": "LEGAL",
    "LAWYER": "LEGAL",
    "EMPLOYED": "OTHER",  # no info — keep as OTHER
    "SELF-EMPLOYED": "SELF-EMPLOYED",
    "REG. REP": "FINANCE / INVESTMENT",
    "GP": "FINANCE / INVESTMENT",  # General Partner
    "SALE": "SALES / MARKETING",
    "ACCOUNT": "ACCOUNTING / TAX",
    "MFG": "BUSINESS / ENTREPRENEUR",
    "VENTURER": "FINANCE / INVESTMENT",
    "HEALTH": "MEDICAL / HEALTHCARE",
    "PROGRAM": "MANAGEMENT",
    "ASSOC": "MANAGEMENT",
    "REGISTERED DIETITIAN, HEALTH AND WELLN": "MEDICAL / HEALTHCARE",
    "HOLISTIC WEALTH AND PHILANTHROPIC COAC": "CONSULTING",

    # Final audit: real, readable occupations that the broad regexes cannot
    # place reliably. Exact values keep these decisions easy to review.
    "ACQUISITIONS": "FINANCE / INVESTMENT",
    "ASSET MANAGER": "FINANCE / INVESTMENT",
    "CAPITAL MARKETS": "FINANCE / INVESTMENT",
    "CLAIMS": "INSURANCE",
    "CANDIDATE FOR DC DELEGATE TO CONGRESS": "GOVERNMENT / MILITARY",
    "COMMERCIAL RE AGENT": "REAL ESTATE",
    "DIRECTOR OF ADVANCEMENT": "NONPROFIT / PHILANTHROPY",
    "EVENT CURATOR": "ARTS / ENTERTAINMENT",
    "EVENT PLANNING": "ARTS / ENTERTAINMENT",
    "FILM AND TV": "ARTS / ENTERTAINMENT",
    "FILM PRODUCTION": "ARTS / ENTERTAINMENT",
    "FOUNDING MEMBER": "EXECUTIVE / C-SUITE",
    "FUND RAISING": "NONPROFIT / PHILANTHROPY",
    "HEALTH AND WELLNESS": "MEDICAL / HEALTHCARE",
    "KOI FISH HAIR STYLIST": "ARTS / ENTERTAINMENT",
    "LEADERSHIP COACHING": "CONSULTING",
    "LITIGATION NEUTRAL": "LEGAL",
    "MASTER TOUR GUIDE": "ARTS / ENTERTAINMENT",
    "NUTRITIONIST, ALBUM MAKING": "MEDICAL / HEALTHCARE",
    "PARAPROFESSIONAL": "EDUCATION",
    "PAYMENTS PROFESSIONAL": "FINANCE / INVESTMENT",
    "PAYROLL PROCESSING": "ACCOUNTING / TAX",
    "PROFESSIONAL SPEAKER": "ARTS / ENTERTAINMENT",
    "REGULATORY": "GOVERNMENT / MILITARY",
    "RESIDENTIAL CONNECTIVITY SPECIALIST": "TECHNOLOGY",
    "RETINA SURGERY": "MEDICAL / HEALTHCARE",
    "STEEL DISTRIBUTOR": "BUSINESS / ENTREPRENEUR",
    "TELECOM": "TECHNOLOGY",
    "VICE PRESIDENT, SHOWS": "EXECUTIVE / C-SUITE",
    "VICE PRESIDENT, TRADE SHOWS": "EXECUTIVE / C-SUITE",
    "WEALTH ADVISOR": "FINANCE / INVESTMENT",
    "WHOLESALE LUMBER": "BUSINESS / ENTREPRENEUR",

    # Readable one-off descriptions from the FEC data. Exact overrides avoid
    # broad regexes that could misclassify unrelated occupations.
    "DESIGN AND BUILD": "CONSTRUCTION / TRADES",
    "FOOD AND BEVERAGE CONSUMER RESEARCH": "SALES / MARKETING",
    "HOUSING": "REAL ESTATE",
    "INSTITUTIONAL DISTRIBUTION & CLIENT SE": "SALES / MARKETING",
    "INSTITUTIONAL DISTRIBUTION & CLIENT SERVICES": "SALES / MARKETING",
    "OWNERSHIP": "BUSINESS / ENTREPRENEUR",
}

# Broader second-pass rules for values that remained OTHER.
RECLASSIFY_CATEGORY_RULES = [
    (r'\bATTORNEY\b|\bLAWYER\b|\bLEGAL\b|\bCOUNSEL\b|\bESQ\b', 'LEGAL'),
    (r'\bDOCTOR\b|\bPHYSICIAN\b|\bSURGEON\b|\bMD\b|\bDENTIST\b|\bNURSE\b|\bRN\b|\bPHARMACIST\b|\bVETERINAR', 'MEDICAL / HEALTHCARE'),
    (r'\bENGINEER\b|\bSOFTWARE\b|\bDEVELOPER\b|\bPROGRAMMER\b|\bIT\b|\bTECH\b', 'TECHNOLOGY'),
    (r'\bPROFESSOR\b|\bTEACHER\b|\bEDUCATOR\b|\bPRINCIPAL\b|\bDEAN\b|\bACADEMIC\b', 'EDUCATION'),
    (r'\bREAL ESTATE\b|\bREALTOR\b|\bBROKER\b|\bPROPERT', 'REAL ESTATE'),
    (r'\bACCOUNTANT\b|\bCPA\b|\bAUDITOR\b|\bBOOKKEEPER\b', 'FINANCE / INVESTMENT'),
    (r'\bBANKER\b|\bINVEST\b|\bFINANC\b|\bTRADER\b|\bANALYST\b|\bHEDGE\b|\bPORTFOLIO\b', 'FINANCE / INVESTMENT'),
    (r'\bCONSULTANT\b|\bADVISOR\b', 'CONSULTING'),
    (r'\bRABBI\b|\bPASTOR\b|\bMINISTER\b|\bCLERGY\b|\bPRIEST\b', 'RELIGIOUS'),
    (r'\bWRITER\b|\bAUTHOR\b|\bJOURNALIST\b|\bEDITOR\b|\bREPORTER\b|\bPUBLISH', 'ARTS / ENTERTAINMENT'),
    (r'\bARCHITECT\b', 'ARTS / ENTERTAINMENT'),
    # COUNSELOR is decided by its qualifier in CATEGORY_RULES (school vs
    # clinical); a bare or unknown-kind COUNSELOR stays OTHER
    (r'\bPSYCHOLOG\b|\bTHERAPIST\b|\bSOCIAL WORK\b', 'MEDICAL / HEALTHCARE'),
    (r'\bSALES\b|\bMARKETING\b|\bADVERTIS', 'SALES / MARKETING'),
    (r'\bEXECUTIVE\b|\bCEO\b|\bCFO\b|\bCOO\b|\bPRESIDENT\b|\bDIRECTOR\b', 'EXECUTIVE / C-SUITE'),
    (r'\bPILOT\b|\bAVIAT', 'TRANSPORTATION'),
    (r'\bPHILANTHROP\b|\bNON.?PROFIT\b|\bNGO\b', 'NONPROFIT / PHILANTHROPY'),
]
