"""Occupation category regex rules — ORDER MATTERS, first match wins."""
import re

CATEGORY_RULES = [
    # status categories override profession
    ('RETIRED', r'^RETIRED$'),
    ('NOT EMPLOYED', r'^NOT EMPLOYED$'),
    ('STUDENT', r'^STUDENT$'),
    ('HOMEMAKER', r'^HOMEMAKER$|^HOUSEWIFE$|^STAY.AT.HOME|^MOM$|^SAHM$'),
    ('SELF-EMPLOYED', r'^SELF-EMPLOYED$'),

    # professional categories — more specific before broader
    ('LEGAL',
     r'ATTORNEY|LAWYER|JUDGE|PARALEGAL|LEGAL|COUNSEL|SOLICITOR|JURIS'
     r'|ESQUIRE|\bESQ\b|ARBITRATOR|MEDIATOR|LAW CLERK'),

    ('MEDICAL / HEALTHCARE',
     # physicians and specialists
     r'PHYSICIAN|DOCTOR|SURGEON|DENTIST|DENTAL|NURSE|PHARMACIST|PSYCHOLOGIST'
     r'|THERAPIST|MEDICAL|HEALTHCARE|HOSPITAL|EMT|PARAMEDIC'
     r'|RADIOLOG|PEDIATRIC|OPHTHALMOLOG|ANESTHESIOLOG|PODIATRI'
     r'|ORTHODONTI|PERIODONTI|DERMATOLOG|VETERINAR|UROLOG|CARDIOLOG'
     r'|ENDODONTI|OPTOMETRI|PSYCHIATRI|NEUROLOG|ONCOLOG|PATHOLOG'
     r'|RHEUMATOLOG|GASTROENTEROLOG|PULMONOLOG|HEMATOLOG|GYNECOLOG|OB.?GYN'
     r'|OBSTETRICI|NEONATOLOG|GERIATRIC|PALLIATIVE|PSYCHOANALYS'
     # allied health
     r'|SOCIAL WORK|CLINICAL SOCIAL|HEALTH CARE|HOME CARE|HEALTH COACH'
     r'|BEHAVIOR ANALYS|SPEECH PATHOLOG|SPEECH LANGUAGE'
     r'|PHYSICAL THERAP|OCCUPATIONAL THERAP'
     r'|PROVIDER|PRACTITIONER'),

    ('FINANCE / INVESTMENT',
     r'FINANCE|FINANCIAL|INVEST\w*|BANKER|BANKING|PORTFOLIO'
     r'|PRIVATE EQUITY|VENTURE CAPITAL|SECURITIES|TRADER|BROKER|TREASURER'
     r'|TRADING|WEALTH MANAG|TRUST ADMIN|TRUST ADMINISTRATION'
     r'|CREDIT ANALYS|COMMODITIES|LENDING|\bLENDER\b|FIXED INCOME'
     r'|FAMILY OFFICE|INV MGR|ACTUAR|\bANALYST\b'),

    ('REAL ESTATE',
     r'REAL ESTATE|PROPERTY|REALTY|REALTOR|LANDLORD|REAL ESTSTE'
     r'|REAL EATATE|REAL RSTATE|HOUSING DEVELOP|MORTGAGE LOAN'
     r'|LAND DEVELOPER|HOME DEVELOPER|HOTEL DEVELOPER|R/E DEVELOP'
     r'|\bBUILDER/DEVELOPER\b|\bBUILDER DEVELOPER\b'),

    ('EXECUTIVE / C-SUITE',
     r'CEO|COO|CTO|CIO|CMO|CDO|CFO|\bCHROO?\b|EXECUTIVE|PRESIDENT|\bCHAIR(?:MAN|WOMAN|PERSON)?\b'
     r'|VICE PRESIDENT|DIRECTOR|PARTNER|FOUNDER|CHIEF'
     r'|PRINCIPAL|\bSENIOR VP\b|\bCO-CHAIRMAN\b|CHAIRMAN EMERITUS'
     r'|MANAGING MEMBER|MANAGING DIRECTOR|MANAGING PARTNER'
     r'|HEAD OF|BOARD MEMBER|COMMISSIONER'),

    ('BUSINESS / ENTREPRENEUR',
     r'BUSINESS OWNER|ENTREPRENEUR|\bOWNER\b|BUSINESS|SMALL BUSINESS|FRANCHISE'
     r'|MERCHANT|MANUFACTURER|MANUFACTURING|\bWHOLESAL|\bRETAIL\b'
     r'|AUTO DEALER|CAR DEALER|AUTOMOTIVE DEALER|AUTOMOTIVE'
     r'|IMPORT.?EXPORT|JEWEL|RECYCLING|SCRAP METAL|E-COMMERCE'
     r'|HANDBAG|DISTRIBUTOR'),

    ('TECHNOLOGY',
     r'SOFTWARE|ENGINEER|PROGRAMMER|DEVELOPER|TECHNOLOGY|TECH'
     r'|\bIT\b|DATA SCIEN|DATA ANALY|COMPUTER|CYBER|NETWORK'
     r'|SYSTEM|DEVOPS|CLOUD|\bUX\b|\bUI\b|WIRELESS|INVENTOR'),

    ('ACCOUNTING / TAX',
     r'\bCPA\b|ACCOUNTANT|ACCOUNTING|\bTAX\b|AUDITOR|BOOKKEEPER'
     r'|CONTROLLER|COMPTROLLER'),

    ('EDUCATION',
     r'TEACHER|PROFESSOR|EDUCATOR|INSTRUCTOR|TUTOR|LIBRARIAN'
     r'|SCHOOL|UNIVERSITY|COLLEGE|FACULTY|LECTURER|ACADEMIC'
     r'|EDUCATIONAL SPECIALIST|HIGHER EDUCATION|\bINTERN\b'),

    ('CONSULTING',
     r'CONSULTANT|CONSULTING|ADVISOR|ADVISORY|ADVISER|STRATEGIST'),

    ('SALES / MARKETING',
     r'SALES|MARKETING|ADVERTISING|PUBLIC RELATION'
     r'|\bBRAND\b|MEDIA|COMMUNICATIONS|PUBLICIST'
     r'|TRAVEL AGENT|RECRUITER|TALENT AGENT|FUNDRAIS'
     r'|PLANNED GIVING|CORPORATE OUTREACH|CORPORATE RELATIONS'
     r'|CUSTOMER SUCCESS|MARKET RESEARCH'),

    ('INSURANCE',
     r'INSURANCE'),

    ('RELIGIOUS',
     r'RABBI|PASTOR|CLERGY|MINISTER|PRIEST|IMAM|CHAPLAIN|CHURCH|CANTOR'),

    ('GOVERNMENT / MILITARY',
     r'GOVERNMENT|MILITARY|ARMY|NAVY|AIR FORCE|FEDERAL'
     r'|STATE EMPLOY|CITY EMPLOY|POLITICAL|POLITICIAN|LOBBYIST|POLICY'
     r'|INVESTIGATOR|REGULATORY|COURT RECEIVER'),

    ('ARTS / ENTERTAINMENT',
     r'ARTIST|WRITER|AUTHOR|MUSICIAN|ACTOR|PRODUCER|DESIGNER'
     r'|PHOTOGRAPHER|ENTERTAINMENT|FILMMAKER|PUBLISHER|PUBLISHING'
     r'|EDITOR|EVENT PLANNER|EVENT PRODUCTION|OPERA SINGER'
     r'|INTERIOR DESIGN|INTERIOR ARCHITECT|CREATIVE|FASHION'
     r'|BEAUTY|SPORTS|PHOTOGRAPHY|\bDJ\b|ARCHITECTURE|\bARCHITECT\b'),

    ('SCIENCE / RESEARCH',
     r'SCIENTIST|RESEARCHER|CHEMIST|PHYSICIST|BIOLOGIST'
     r'|ECONOMIST|LABORATORY|GEOLOGIST|HYDROGEOLOG|ARCHAEOLOG'
     r'|\bSCIENCE\b'),

    ('MANAGEMENT',
     r'MANAGER|MANAGEMENT|SUPERVISOR|ADMINISTRATOR|OPERATIONS'
     r'|ADMIN|ADMINISTRATION|SECRETARY|ORGANIZER|OFFICE ADMIN'
     r'|\bASSISTANT\b|ASSOCIATE STAFF'),

    ('CONSTRUCTION / TRADES',
     r'CONSTRUCT|CONTRACTOR|PLUMB|ELECTRICIAN|CARPENTER'
     r'|HVAC|ROOFING|WELDING|MECHANIC|BUILDER|MAINTENANCE'),

    ('AGRICULTURE',
     r'FARM|RANCH|AGRICULTURE|AGRI'),

    ('TRANSPORTATION',
     r'PILOT|DRIV\w+|TRUCKING|SHIPPING|LOGISTICS|TRANSPORT|AVIATION|MOVER'),

    ('FOOD / HOSPITALITY',
     r'CHEF|COOK|RESTAURANT|HOTEL|BAKERY|CATER|SERVER'
     r'|WAITER|HOSPITALITY|FOOD SERVICE|BARISTA'),

    ('NONPROFIT / PHILANTHROPY',
     r'VOLUNTEER|PHILANTHROPIST|NONPROFIT|NON-PROFIT|NON PROFIT'
     r'|FOUNDATION|CHARITY|NGO|PHILANTHROPY|SOCIAL ACTIVIST'),

]

# pre-compiled for performance
CATEGORY_PATTERNS = [(cat, re.compile(pat)) for cat, pat in CATEGORY_RULES]

VALID_CATEGORIES = frozenset(
    [cat for cat, _ in CATEGORY_RULES]
    + [
        'OTHER',
        'POLITICAL COMMITTEE', 'CONGRESSIONAL CAMPAIGN',
        'SENATE CAMPAIGN', 'POLITICAL ACTION COMMITTEE',
        'PARTY ORGANIZATION',
        # written by the entity classifier (not CATEGORY_RULES) for
        # ORGANIZATION entities — the gate must list it or every run
        # reports it as invalid
        'ORGANIZATION',
    ]
)
