"""Explicit category overrides for occupations the regex rules misclassify."""

CATEGORY_OVERRIDES = {
    # technology; bare "DEVELOPER" in FEC data is usually software
    "SOFTWARE DEVELOPER": "TECHNOLOGY",
    "SOFTWARE EXECUTIVE": "TECHNOLOGY",
    "SOFTWARE RELEASE ANALYST": "TECHNOLOGY",
    "SOFTWARE DEVELOPMENT MANAGER": "TECHNOLOGY",
    "QUANT DEVELOPER": "TECHNOLOGY",
    "DEVELOPER": "TECHNOLOGY",
    "DEVELOPER/DESIGNER": "TECHNOLOGY",
    "DATABASE DEVELOPER": "TECHNOLOGY",
    "DATABASE ANALYTICS": "TECHNOLOGY",

    # construction / trades; CONTRACTOR is caught by the EXECUTIVE regex
    "CONTRACTOR": "CONSTRUCTION / TRADES",
    "GENERAL CONTRACTOR": "CONSTRUCTION / TRADES",
    "ELECTRICAL CONTRACTOR": "CONSTRUCTION / TRADES",
    "ROOFING CONTRACTOR": "CONSTRUCTION / TRADES",
    "FLOORING CONTRACTOR": "CONSTRUCTION / TRADES",
    "FLOORING": "CONSTRUCTION / TRADES",
    "ARCHITECT": "CONSTRUCTION / TRADES",
    "INTERIOR ARCHITECT": "CONSTRUCTION / TRADES",

    # CHIROPRACTOR also caught by the EXECUTIVE regex
    "CHIROPRACTOR": "MEDICAL / HEALTHCARE",

    # finance
    "PRIVATE WEALTH ADVISOR": "FINANCE / INVESTMENT",
    "FUND MANAGER": "FINANCE / INVESTMENT",
    "MONEY MANAGEMENT": "FINANCE / INVESTMENT",
    "MONEY MANAGER": "FINANCE / INVESTMENT",
    "ECONOMIST": "FINANCE / INVESTMENT",
    "CFP": "FINANCE / INVESTMENT",

    # sales / marketing
    "BUSINESS DEVELOPMENT MANAGER": "SALES / MARKETING",
    "BUSINESS DEVELOPMENT": "SALES / MARKETING",
    "HEAD OF BUSINESS DEVELOPMENT": "SALES / MARKETING",
    "ACCOUNT EXECUTIVE": "SALES / MARKETING",

    # management
    "HUMAN RESOURCES": "MANAGEMENT",
    "CONSTRUCTION MANAGER": "MANAGEMENT",

    # executive
    "VP OF MARKETING": "EXECUTIVE / C-SUITE",
    "CHIEF DEVELOPMENT OFFICER": "EXECUTIVE / C-SUITE",

    # legal; MEDIATION contains MEDIA so the SALES/MARKETING regex fires
    "MEDIATION": "LEGAL",
    "MEDIATOR": "LEGAL",
    "FAMILY MEDIATION": "LEGAL",
    "FAMILY MEDIATOR": "LEGAL",

    "RESTAURATEUR": "FOOD / HOSPITALITY",
    "EDUCATION": "EDUCATION",

    # real estate development
    "OWNER/DEVELOPER": "REAL ESTATE",
    "PROPERTY DEVELOPMENT": "REAL ESTATE",
    "SOLAR DEVELOPER": "CONSTRUCTION / TRADES",
    "AFFORDABLE HOUSING DEVELOPER": "REAL ESTATE",

    # medical, missed by regex
    "NEPHROLOGIST": "MEDICAL / HEALTHCARE",
    "PHARMACY SERVICES": "MEDICAL / HEALTHCARE",
    "PHARMACY": "MEDICAL / HEALTHCARE",
    "PHARMACIST CONSULTANT": "MEDICAL / HEALTHCARE",
    "ORAL SURGEON": "MEDICAL / HEALTHCARE",
    "ALLERGIST": "MEDICAL / HEALTHCARE",
    "INTERNIST": "MEDICAL / HEALTHCARE",

    # government, missed by regex
    "COUNCILMEMBER": "GOVERNMENT / MILITARY",
    "CITY COUNCIL MEMBER": "GOVERNMENT / MILITARY",
    "COUNCIL MEMBER": "GOVERNMENT / MILITARY",
    "ELECTED OFFICIAL": "GOVERNMENT / MILITARY",
    "PUBLIC OFFICIAL": "GOVERNMENT / MILITARY",
    "MAYOR": "GOVERNMENT / MILITARY",
    "ALDERMAN": "GOVERNMENT / MILITARY",

    "PROPANE MARKETER": "SALES / MARKETING",
    "IMPORTER": "SALES / MARKETING",

    # real estate development variants
    "COMMERCIAL REAL ESTATE DEVELOPMENT": "REAL ESTATE",
    "REAL ESTATE DEVELOPMENT AND MANAGEMENT": "REAL ESTATE",
    "HOUSING DEVELOPMENT": "REAL ESTATE",
    "HOMELESS HOUSING": "REAL ESTATE",
    "COMMUNITY BUILDING": "REAL ESTATE",

    # executive typos and variants
    "CORP EXEC": "EXECUTIVE / C-SUITE",
    "EXEC VP": "EXECUTIVE / C-SUITE",
    "EXECUIVE": "EXECUTIVE / C-SUITE",
    "CORPORATE OFFICER": "EXECUTIVE / C-SUITE",
    "SENIOR ASSOCIATE": "EXECUTIVE / C-SUITE",
    "MANAGING MENBER": "EXECUTIVE / C-SUITE",
    "CORPORATE FIDUCIARY": "EXECUTIVE / C-SUITE",

    "CONSULTANCY": "CONSULTING",

    # arts / entertainment
    "ART GALLERIST": "ARTS / ENTERTAINMENT",
    "ENTERTAINER": "ARTS / ENTERTAINMENT",
    "DECORATOR": "ARTS / ENTERTAINMENT",
    "CORPORATE STORYTELLER": "ARTS / ENTERTAINMENT",
    "TOUR GUIDE": "ARTS / ENTERTAINMENT",
    "SUSTAINABLE DESIGN": "ARTS / ENTERTAINMENT",
    "MEETING PLANNER": "ARTS / ENTERTAINMENT",
    "INTERNATIONAL PARTY PLANNER": "ARTS / ENTERTAINMENT",

    # business
    "AUTOMOBILE DEALER": "BUSINESS / ENTREPRENEUR",
    "RETAILER": "BUSINESS / ENTREPRENEUR",
    "LUMBER BIZ": "BUSINESS / ENTREPRENEUR",
    "BUSIENSS": "BUSINESS / ENTREPRENEUR",
    "INTERNATIONAL COMMERCE": "BUSINESS / ENTREPRENEUR",
    "APARTMENTS": "REAL ESTATE",
    "HOMEBUILDING": "CONSTRUCTION / TRADES",

    # education
    "DEAN": "EDUCATION",
    "TEACHING": "EDUCATION",
    "STUDENT CUSTODIAN": "EDUCATION",

    # medical
    "REGISTERED DIETITIAN": "MEDICAL / HEALTHCARE",
    "HOLISTIC NUTRITIONIST": "MEDICAL / HEALTHCARE",
    "HEALTH COCH": "MEDICAL / HEALTHCARE",
    "CAREGIVER": "MEDICAL / HEALTHCARE",
    "CLINICAL DEVELOPMENT": "MEDICAL / HEALTHCARE",

    # management
    "MANAGET": "MANAGEMENT",
    "PROJECT MGR": "MANAGEMENT",
    "ACCOUNT CLERK": "MANAGEMENT",
    "OFFICE HELP": "MANAGEMENT",
    "PROP MNGMT": "MANAGEMENT",
    "RGM LEAD": "MANAGEMENT",

    "SW EGIEER": "TECHNOLOGY",
    "APP DEVELOPMENT": "TECHNOLOGY",

    # finance
    "GROWTH EQUITY": "FINANCE / INVESTMENT",
    "VENTURE CSPITALIST": "FINANCE / INVESTMENT",
    "UNDERWRITING": "FINANCE / INVESTMENT",

    "MARKETER": "SALES / MARKETING",

    # government
    "PUBLIC ADJUSTER": "GOVERNMENT / MILITARY",
    "PROGRAM SPECIALIST": "GOVERNMENT / MILITARY",
    "COMP CLAIMS REFEREE": "GOVERNMENT / MILITARY",
    "INFORMATION RESEARCH SPECIALIST": "GOVERNMENT / MILITARY",
    "JUDICIAL RECEIVER": "LEGAL",

    "FREELANCER": "SELF-EMPLOYED",
    "PET SITTER": "SELF-EMPLOYED",

    # batch 2

    # executive
    "DEPUTY MANAGING DIRECTOR": "EXECUTIVE / C-SUITE",
    "CO PRES": "EXECUTIVE / C-SUITE",
    "FOOD MFG EXEC": "EXECUTIVE / C-SUITE",
    "CH BD": "EXECUTIVE / C-SUITE",
    "EXEC RECRUITING/BD": "EXECUTIVE / C-SUITE",
    "SVP, MUSIC & CELEBRITY TALENT": "EXECUTIVE / C-SUITE",
    "FIN MGMT": "FINANCE / INVESTMENT",
    "FIN ADV": "FINANCE / INVESTMENT",
    "FINACIAL": "FINANCE / INVESTMENT",
    "PRIVATE WEALTH": "FINANCE / INVESTMENT",
    "PRIVATE CREDIT ALLOCATOR": "FINANCE / INVESTMENT",
    "RESTRUCTURING": "FINANCE / INVESTMENT",
    "AQUISITIONS": "FINANCE / INVESTMENT",
    "FUNDING": "FINANCE / INVESTMENT",

    # legal
    "ATROENEY": "LEGAL",
    "ATTOENY": "LEGAL",
    "ATT'Y": "LEGAL",
    "PROSECUTOR": "LEGAL",
    "FIDUCIARY": "LEGAL",

    # medical / science
    "NUCLEAR HYDROLOGIST": "SCIENCE / RESEARCH",
    "BIOSTATISTICIAN": "SCIENCE / RESEARCH",
    "PSYCHOMETRIST": "MEDICAL / HEALTHCARE",
    "LONG TERM CARE AND REHABILITATION FACI": "MEDICAL / HEALTHCARE",
    "SENIOR LIVING": "MEDICAL / HEALTHCARE",
    "MENTAL HEALTH": "MEDICAL / HEALTHCARE",
    "CLINICAL TRIALS": "MEDICAL / HEALTHCARE",
    "HESLTHCARE": "MEDICAL / HEALTHCARE",
    "PHYT": "MEDICAL / HEALTHCARE",

    # insurance
    "INSURANCE BROKER": "INSURANCE",
    "INSURANCE": "INSURANCE",
    "COMPLEX CLAIMS SPECIALIST": "INSURANCE",
    "ADJUSTER": "INSURANCE",

    # real estate
    "REAL ESTATE": "REAL ESTATE",
    "REAL EATSTE": "REAL ESTATE",
    "REAL ESTATE DEVELOPMENT": "REAL ESTATE",
    "CRE APPRAISER": "REAL ESTATE",
    "APPRAISER": "REAL ESTATE",
    "MARINA OPERATOR": "REAL ESTATE",
    "SELF STG MGMT & DVLPMT": "REAL ESTATE",
    "HOME IMPROVEMENT": "CONSTRUCTION / TRADES",

    # sales / marketing
    "MARKEITNG": "SALES / MARKETING",
    "BRANDING": "SALES / MARKETING",
    "BRANDED MERCH": "SALES / MARKETING",
    "MERCH AND PROMOTIONAL PRODUCTS": "SALES / MARKETING",
    "HEADHUNTER": "SALES / MARKETING",
    "CUSTOMER SERVICE": "SALES / MARKETING",
    "LOAN OFFICER": "SALES / MARKETING",
    "AUCTIONEER": "SALES / MARKETING",

    # education
    "INSTRUCTIONAL COACH": "EDUCATION",
    "LANG ARTS SPECIALIST": "EDUCATION",
    "BASKETBALL COACH": "EDUCATION",
    "GRAD STUDENT": "STUDENT",
    "SENIOR FELLOW": "EDUCATION",

    # management
    "PRODUCT MANAGEENT": "MANAGEMENT",
    "PROGRAM ASSOCIATE": "MANAGEMENT",
    "OPS": "MANAGEMENT",
    "PACKAGE HANDLER": "MANAGEMENT",
    "CLERK": "MANAGEMENT",
    "OFFICE STAFF": "MANAGEMENT",
    "OPERATOR": "MANAGEMENT",
    "EMPLOYEE": "MANAGEMENT",
    "MANAY": "MANAGEMENT",
    "MD LATAM": "MANAGEMENT",

    # government
    "CONGRESSIONAL CANDIDATE": "GOVERNMENT / MILITARY",
    "STATE REP": "GOVERNMENT / MILITARY",
    "JP #5": "GOVERNMENT / MILITARY",
    "GOV'T RELATIONS": "GOVERNMENT / MILITARY",
    "LANDMAN": "GOVERNMENT / MILITARY",

    # arts / entertainment
    "HAIR STYLIST": "ARTS / ENTERTAINMENT",
    "FLORIST": "ARTS / ENTERTAINMENT",
    "TAILOR": "ARTS / ENTERTAINMENT",
    "VIDEO": "ARTS / ENTERTAINMENT",
    "BROADCAST PRODUCTION": "ARTS / ENTERTAINMENT",
    "FIELD PROD": "ARTS / ENTERTAINMENT",
    "PRODUCT DESIGN": "ARTS / ENTERTAINMENT",
    "MULTI FAMILY DESIGN": "ARTS / ENTERTAINMENT",
    "YOGA FITNESS": "ARTS / ENTERTAINMENT",
    "LIFE COACH": "CONSULTING",
    "MARRIAGE COACH": "CONSULTING",
    "FACILITATOR": "CONSULTING",

    # business
    "AUTO": "BUSINESS / ENTREPRENEUR",
    "AUTOMTIVE": "BUSINESS / ENTREPRENEUR",
    "IMPORT": "BUSINESS / ENTREPRENEUR",
    "SCRAP": "BUSINESS / ENTREPRENEUR",
    "PAPER CONVERTER": "BUSINESS / ENTREPRENEUR",
    "APPAREL": "BUSINESS / ENTREPRENEUR",
    "JEWLERY": "BUSINESS / ENTREPRENEUR",
    "CLEANNG SERVICE": "BUSINESS / ENTREPRENEUR",
    "ENERGY": "BUSINESS / ENTREPRENEUR",
    "POWER": "BUSINESS / ENTREPRENEUR",
    "OIL & GAS": "BUSINESS / ENTREPRENEUR",
    "DIGITAL TRANSFORMATION": "TECHNOLOGY",

    "ISRAEL TOUR OPERATOR": "FOOD / HOSPITALITY",

    # nonprofit
    "FUND-RAISING": "NONPROFIT / PHILANTHROPY",
    "JEWISH PROFESSIONAL": "NONPROFIT / PHILANTHROPY",
    "DIR OF PROGRAMMING": "NONPROFIT / PHILANTHROPY",
    "DIRECT OF CURRICULUM DEVELOPMENT": "EDUCATION",

    # science
    "MEMBER OF RESEARCH STAFF": "SCIENCE / RESEARCH",
    "PSYCHOLOGY": "SCIENCE / RESEARCH",

    # batch 3: final stragglers
    "DEVELOPMENT": "NONPROFIT / PHILANTHROPY",  # fundraising context in this data
    "INTERNATIONAL DEVELOPMENT": "NONPROFIT / PHILANTHROPY",
    "VP OF DEVELOPMENT": "NONPROFIT / PHILANTHROPY",
    "INVESTMENT MANAGEMENT": "FINANCE / INVESTMENT",
    "MANAGING PARTNER": "EXECUTIVE / C-SUITE",
    "OWNER": "BUSINESS / ENTREPRENEUR",
    "ENTREPRENEUR": "BUSINESS / ENTREPRENEUR",
    "ATTORNEY": "LEGAL",
    "LAWYER": "LEGAL",
    "EMPLOYED": "OTHER",  # no info — keep as OTHER
    "SELF-EMPLOYED": "SELF-EMPLOYED",
    "REG. REP": "FINANCE / INVESTMENT",
    "GP": "FINANCE / INVESTMENT",  # General Partner
    "SALE": "SALES / MARKETING",
    "ACCOUNT": "ACCOUNTING / TAX",
    "MFG": "BUSINESS / ENTREPRENEUR",
    "VENTURER": "FINANCE / INVESTMENT",
    "HEALTH": "MEDICAL / HEALTHCARE",
    "PROGRAM": "MANAGEMENT",
    "ASSOC": "MANAGEMENT",
    "REGISTERED DIETITIAN, HEALTH AND WELLN": "MEDICAL / HEALTHCARE",
    "HOLISTIC WEALTH AND PHILANTHROPIC COAC": "CONSULTING",
}
