"""Occupation cross-field rules: occupation-employer mappings and job-title sets."""
from fec.config.constants import (
    OCCUPATION_AS_EMPLOYER as _OCCUPATION_AS_EMPLOYER,
    REFUSAL_EMPLOYERS as _REFUSAL_EMPLOYERS,
)


# Explicit refusals keep NOT DISCLOSED; other fixes to that value are junk.
OCCUPATION_REFUSAL_INPUTS = frozenset({
    'PRIVATE', 'CONFIDENTIAL', 'PREFER NOT TO ANSWER',
    'DECLINED TO ANSWER', 'MYOB', 'TMI',
})

# Employer status -> occupation/category when occupation is missing.
OCCUPATION_FROM_EMPLOYER = {
    'RETIRED': ('RETIRED', 'RETIRED'),
    'SELF-EMPLOYED': ('SELF-EMPLOYED', 'SELF-EMPLOYED'),
    'NOT EMPLOYED': ('NOT EMPLOYED', 'NOT EMPLOYED'),
}

# Occupation status -> employer during the field-level pass.
EMPLOYER_FROM_OCCUPATION = {
    'RETIRED': 'RETIRED',
    'NOT EMPLOYED': 'NOT EMPLOYED',
    'HOMEMAKER': 'NOT EMPLOYED',
    'SELF-EMPLOYED': 'SELF-EMPLOYED',
    'STUDENT': 'STUDENT',
}

# Donor consistency keeps homemaker distinct and handles aliases.
FINAL_EMPLOYER_FROM_OCCUPATION = {
    **EMPLOYER_FROM_OCCUPATION,
    'HOMEMAKER': 'HOMEMAKER',
    'HOUSEWIFE': 'HOMEMAKER',
    'UNEMPLOYED': 'NOT EMPLOYED',
}
EMPLOYER_FROM_CATEGORY = {
    category: FINAL_EMPLOYER_FROM_OCCUPATION[category]
    for category in ('RETIRED', 'NOT EMPLOYED', 'HOMEMAKER', 'STUDENT', 'SELF-EMPLOYED')
}

SWAP_JOB_TITLES = _OCCUPATION_AS_EMPLOYER | frozenset({
    'MANAGER', 'PARTNER', 'ADMINISTRATOR',
    'PRESIDENT', 'VICE PRESIDENT', 'VP', 'DIRECTOR', 'EXECUTIVE',
    'OFFICER', 'CEO', 'CFO', 'COO', 'CTO', 'CMO',
})

OCCUPATION_KEYWORDS = _OCCUPATION_AS_EMPLOYER | frozenset({
    'ATTORNEY', 'LAWYER', 'PARTNER', 'MANAGER', 'ADMINISTRATOR',
    'PRESIDENT', 'DIRECTOR', 'EXECUTIVE', 'PHYSICIAN', 'ACCOUNTANT',
    'CONSULTANT', 'ENGINEER', 'OFFICER', 'ANALYST', 'ADVISOR',
    'COUNSEL', 'DENTIST', 'SURGEON', 'BROKER', 'AGENT',
    'CLAIMS', 'CPA', 'OWNER', 'MANAGING PARTNER', 'MANAGING DIRECTOR',
    'PAC MANAGER', 'INSURANCE BROKER', 'INSURANCE AGENT', 'REAL ESTATE',
    'INVESTMENT MANAGEMENT', 'FINANCE', 'MARKETING', 'MANAGEMENT',
    'SALES', 'CASHIER', 'DESIGNER', 'CATER', 'CATERER', 'WRITER',
    'ARTIST', 'PSYCHOLOGIST', 'THERAPIST', 'PROFESSOR',
})

FINAL_SHORT_OCCUPATIONS = frozenset({
    'MD', 'VP', 'PA', 'RN', 'IT', 'PR', 'HR', 'AI', 'DJ', 'DO', 'GP', 'GM',
})
FINAL_JUNK_EMPLOYERS = frozenset({
    'VARIOUS', 'JOB', 'A', 'EMP', 'N', 'MULTIPLE', 'OTHER',
})
FINAL_NULL_EMPLOYERS = _REFUSAL_EMPLOYERS | frozenset({
    'N/A', 'NA', 'N A', 'NONE', 'NOT APPLICABLE', 'NOT APPLICAABLE',
    'NOT DISCLOSED', 'INFORMATION REQUESTED',
    'INFORMATION REQUESTED PER BEST EFFORTS', 'PHYSICAN', 'SELP EMPLOYED',
})
WEB_ARTIFACT_OCCUPATIONS = frozenset({
    'LOADING', 'ACMIO', 'REMD', 'SWAP MEET', 'UOOO[',
    # a joke with no job in it (SPIES, DAVID @ SANDHURST); once nulled, the
    # donor-stage same-employer fill restores the role he files there
    'BIG BOY',
})

KNOWN_COMPANY_OCCUPATIONS = frozenset({
    'ARCH INSURANCE', 'BROWN & BROWN', 'DANZIGER & DE LLANO LLP',
    'NNA SERVICES LLC', 'BAKER TILLY', 'AMERICAN EXPRESS',
    'NFI INDUSTRIES', 'SKYRISE PROPERTIES', 'PAYROLL COMPANY',
})

HOMEMAKER_EMPLOYER_VALUES = frozenset({
    'HOMEMAKER', 'HOUSEWIFE', 'HOUSWIFE', 'HOUSEWIVES',
    'STAY AT HOME MOM', 'STAY AT HOME DAD',
})

