"""Occupation value rules: normalization, fixes, and cross-field mappings."""
from fec.config.constants import (
    OCCUPATION_AS_EMPLOYER as _OCCUPATION_AS_EMPLOYER,
    REFUSAL_EMPLOYERS as _REFUSAL_EMPLOYERS,
)
from fec.config.employers import EMPLOYER_NORMALIZE as _EMPLOYER_NORMALIZE

OCCUPATION_NORMALIZE = {
    # EMPLOYER_NORMALIZE merge must stay first — entries below override it.
    **_EMPLOYER_NORMALIZE,

    # homemaker
    'HOMEMAKER': 'HOMEMAKER',
    'HOME MAKER': 'HOMEMAKER',
    'HOME-MAKER': 'HOMEMAKER',
    'HOMEKEEPER': 'HOMEMAKER',
    'HOMEKEEPR': 'HOMEMAKER',
    'HOME': 'HOMEMAKER',
    'AT HOME': 'HOMEMAKER',
    'SAHM': 'STAY AT HOME MOM',
    'MOM': 'HOMEMAKER',
    # HOUSEWIFE stays HOUSEWIFE — different word
    # STAY AT HOME MOM/DAD stay as-is — different from HOMEMAKER

    # short abbreviations verified from FEC data
    'ART': 'ARTIST',
    'BIZ': 'BUSINESS',
    'CRE': 'COMMERCIAL REAL ESTATE',

    # self-employed typos in the occupation field
    'SELF EMPLOYED EMPLOYED': 'SELF-EMPLOYED',
    'SELFEMPLOYED': 'SELF-EMPLOYED',
    'SLEF': 'SELF-EMPLOYED',
    'SWLF': 'SELF-EMPLOYED',
    'SLEF EMPLOYED': 'SELF-EMPLOYED',
    'SEFL EMPLOYED': 'SELF-EMPLOYED',
    'SELF-EMPLOY': 'SELF-EMPLOYED',
    'SELF EMPLOY': 'SELF-EMPLOYED',

    # legal
    'ATTORNEY AT LAW': 'ATTORNEY',
    'ATTORNEY-AT-LAW': 'ATTORNEY',
    'ATTORNEY/LAWYER': 'ATTORNEY',
    # LAWYER stays LAWYER — legally different from ATTORNEY
    # TRIAL LAWYER / TRIAL ATTORNEY stay — specific types

    # medical: DR/MD live in OCCUPATION_FIXES
    # DOCTOR stays DOCTOR — different word from PHYSICIAN

    # executive titles
    'CE0': 'CEO',  # zero for O
    'C.E.O.': 'CEO',
    'C.E.O': 'CEO',
    'CHIEF EXECUTIVE OFFICER': 'CEO',
    'CHIEF EXECUTIVE': 'CEO',
    'CDO': 'CHIEF DEVELOPMENT OFFICER',
    'CMO': 'CHIEF MARKETING OFFICER',
    'CIO': 'CHIEF INVESTMENT OFFICER',
    'CFP': 'CERTIFIED FINANCIAL PLANNER',
    'DDS': 'DENTIST',

    # real estate — forms kept distinct (REALTOR is trademarked; broker is a
    # different license)
    'REALTOR': 'REALTOR',
    'REAL ESTATE AGENT': 'REAL ESTATE AGENT',
    'REAL ESTATE BROKER': 'REAL ESTATE BROKER',

    # BUSINESSMAN / BUSINESSWOMAN / SMALL BUSINESS OWNER stay — different words
    'BUSINESS OWNER': 'BUSINESS OWNER',
    'BUSINESSMAN': 'BUSINESSMAN',
    'BUSINESSWOMAN': 'BUSINESSWOMAN',

    # executive; SENIOR/CORPORATE EXECUTIVE stay — more specific
    'EXEC': 'EXECUTIVE',
    'EXEC.': 'EXECUTIVE',
    'SENIOR EXECUTIVE': 'SENIOR EXECUTIVE',
    'CORPORATE EXECUTIVE': 'CORPORATE EXECUTIVE',

    # VP — expand abbreviations, keep full forms
    'VP': 'VICE PRESIDENT',
    'V.P.': 'VICE PRESIDENT',
    'VICE PRES': 'VICE PRESIDENT',
    'SVP': 'SENIOR VICE PRESIDENT',
    'EVP': 'EXECUTIVE VICE PRESIDENT',

    # chair — keep all forms distinct
    'CHAIRMAN': 'CHAIRMAN',
    'CHAIRWOMAN': 'CHAIRWOMAN',
    'CHAIRPERSON': 'CHAIRPERSON',
    'VICE CHAIRMAN': 'VICE CHAIRMAN',
    'EXECUTIVE CHAIRMAN': 'EXECUTIVE CHAIRMAN',
    'EXEC CHAIRMAN': 'EXECUTIVE CHAIRMAN',
    'EXEC. CHAIRMAN': 'EXECUTIVE CHAIRMAN',
    'CHAIRMAN OF THE BOARD': 'CHAIRMAN OF THE BOARD',

    # consulting; CONSULTING stays — a field, not a typo
    'COMSULTANT': 'CONSULTANT',
    'CONSLTANT': 'CONSULTANT',

    # professor — keep qualifiers
    'ASSOC PROFESSOR': 'ASSOCIATE PROFESSOR',

    # medical typos
    'PHYSICAN': 'PHYSICIAN',
    'PHYSICISN': 'PHYSICIAN',
    'PHYSICAIN': 'PHYSICIAN',

    # real estate typos
    'REAL EATATE': 'REAL ESTATE',
    'REAL ESTSTE': 'REAL ESTATE',
    'REAL ESTAE': 'REAL ESTATE',
    'REALESTATE': 'REAL ESTATE',

    # consulting typos; CONSULTANCY stays — a business form, not a typo
    'CONSJLTANT': 'CONSULTANT',
    'COMSUJTANT': 'CONSULTANT',
    'CONSUTLANT': 'CONSULTANT',
    'CONSUTANT': 'CONSULTANT',
    'CONSULTENT': 'CONSULTANT',

    # legal typos
    'ATTORМEY': 'ATTORNEY',  # Cyrillic М
    'ATTONREY': 'ATTORNEY',
    'ATTORMEY': 'ATTORNEY',
    'ATTORENY': 'ATTORNEY',
    'ATORNEY': 'ATTORNEY',
    'ATTOREY': 'ATTORNEY',
    'AWYER': 'LAWYER',

    # management typos
    'MANAGMENT': 'MANAGEMENT',
    'MANAGMNT': 'MANAGEMENT',
    'MANGER': 'MANAGER',

    # engineer typos
    'ENFINEER': 'ENGINEER',
    'ENGINEEER': 'ENGINEER',
    'ENGINER': 'ENGINEER',
    'ENGINEE': 'ENGINEER',
    'ENGIEER': 'ENGINEER',
    'ENNGINEER': 'ENGINEER',
    'ENGINEERR': 'ENGINEER',
    'ENGINNEER': 'ENGINEER',
    'ENGINEAR': 'ENGINEER',

    # software engineer typos
    'SOFTWARE ENFINEER': 'SOFTWARE ENGINEER',
    'SOFTWARE ENGINEEER': 'SOFTWARE ENGINEER',
    'SOFTWARE ENGINER': 'SOFTWARE ENGINEER',
    'SOFTWARE ENGINEE': 'SOFTWARE ENGINEER',
    'SOFWARE ENGINEER': 'SOFTWARE ENGINEER',
    'SOFTWRE ENGINEER': 'SOFTWARE ENGINEER',
    'SOFTARE ENGINEER': 'SOFTWARE ENGINEER',
    'SFTWARE ENGINEER': 'SOFTWARE ENGINEER',
    'SOFTWEAR ENGINEER': 'SOFTWARE ENGINEER',
    'SOFTWARE ENGR': 'SOFTWARE ENGINEER',

    # analyst typos
    'ANAYLST': 'ANALYST',
    'ANLYST': 'ANALYST',
    'ANLAYST': 'ANALYST',

    # executive typos
    'EXECTUTIVE': 'EXECUTIVE',
    'EXECTUIVE': 'EXECUTIVE',
    'EXCECUTIVE': 'EXECUTIVE',
    'EXECUTIVRE': 'EXECUTIVE',

    # more medical typos
    'PHYSCIAN': 'PHYSICIAN',
    'PHYISICIAN': 'PHYSICIAN',
    'OPTHAMOLOGIST': 'OPHTHALMOLOGIST',
    'WEALTH MANAGMENT': 'WEALTH MANAGEMENT',
    # near-duplicates: singular/plural, -er/-ing, -or/-ion to one canonical form
    'INVESTMENT BANKING': 'INVESTMENT BANKER',
    'VENTURE CAPITALIST': 'VENTURE CAPITAL',
    'PROPERTY MANAGEMENT': 'PROPERTY MANAGER',
    'REAL ESTATE INVESTING': 'REAL ESTATE INVESTOR',
    'REAL ESTATE INVESTMENTS': 'REAL ESTATE INVESTOR',
    'REAL ESTATE INVESTMENT': 'REAL ESTATE INVESTOR',
    'REAL ESTATE INVESTOR/BUSINESSPERSON': 'REAL ESTATE INVESTOR',
    'REAL ESTATE INVESTOR/DEVELOPER': 'REAL ESTATE INVESTOR/DEVELOPER',
    'REAL ESTATE PROPERTY MANAGER': 'REAL ESTATE MANAGEMENT',
    'REAL ESTATE PROPERTY MANAGEMENT': 'REAL ESTATE MANAGEMENT',
    'REAL ESTATE PROFESSIONAL': 'REAL ESTATE',
    'REAL ESTATE AND INVESTMENT': 'REAL ESTATE INVESTOR',
    'SELF-EMPLOYED CONSULTANT': 'CONSULTANT',

    # typo fixes
    'SW EGIEER': 'SOFTWARE ENGINEER',
    'EXECUIVE': 'EXECUTIVE',
    'MANAGET': 'MANAGER',
    'BUSIENSS': 'BUSINESS',
    'HEALTH COCH': 'HEALTH COACH',
    'VENTURE CSPITALIST': 'VENTURE CAPITAL',
    'MANAGING MENBER': 'MANAGING MEMBER',
    'APP DEVELOPMENT': 'APPLICATION DEVELOPER',
    'PROP MNGMT': 'PROPERTY MANAGER',
    'PROJECT MGR': 'PROJECT MANAGER',
    'CORP EXEC': 'CORPORATE EXECUTIVE',
    'EXEC VP': 'EXECUTIVE VICE PRESIDENT',
    'LUMBER BIZ': 'LUMBER BUSINESS',

    # auto-detected typos (Levenshtein=1 from common occupations)
    'RETITED': 'RETIRED',
    'RETRIRED': 'RETIRED',
    'RETIERED': 'RETIRED',
    'RETRED': 'RETIRED',
    'RETIRD': 'RETIRED',
    'MNAGER': 'MANAGER',
    'PRESIDEN': 'PRESIDENT',
    'JEWLER': 'JEWELER',
    'ATTORNEYS': 'ATTORNEY',
    'ATTORNEYH': 'ATTORNEY',
    'ATRORNEY': 'ATTORNEY',
    'ARTORNEY': 'ATTORNEY',
    'ATRTORNEY': 'ATTORNEY',
    'TTORNEY': 'ATTORNEY',
    'ATTIRNEY': 'ATTORNEY',
    'AATTORNEY': 'ATTORNEY',
    'ATTORNEY`': 'ATTORNEY',
    'REA ESTATE': 'REAL ESTATE',
    'REAL ESTARE': 'REAL ESTATE',
    'REAL,ESTATE': 'REAL ESTATE',
    'REAL ESTAT': 'REAL ESTATE',
    'RAL ESTATE': 'REAL ESTATE',
    'RESL ESTATE': 'REAL ESTATE',
    'REQL ESTATE': 'REAL ESTATE',
    'REAL ESATATE': 'REAL ESTATE',
    'REAL RSTATE DEVELOPER': 'REAL ESTATE DEVELOPER',
    'REWAL ESTATE INVESTOR': 'REAL ESTATE INVESTOR',
    'REAL EATATE MANAGEMENT': 'REAL ESTATE MANAGEMENT',
    'REAL ESTATE/INVESTING': 'REAL ESTATE INVESTOR',
    'REAL ESTATE/OWNER': 'REAL ESTATE OWNER',
    'OHYSICIAN': 'PHYSICIAN',
    'PHYCICIAN': 'PHYSICIAN',
    'PHYSICIA': 'PHYSICIAN',
    'PHISICIAN': 'PHYSICIAN',
    'PHYSICIQN': 'PHYSICIAN',
    'PHYSISIAN': 'PHYSICIAN',
    'EXRCUTIVE': 'EXECUTIVE',
    'EXERCUTIVE': 'EXECUTIVE',
    'EXECUTICVE': 'EXECUTIVE',
    'EXECUTIVEV': 'EXECUTIVE',
    'LQWYER': 'LAWYER',
    'LAQWYER': 'LAWYER',
    'CONSULITANT': 'CONSULTANT',
    'COSULTANT': 'CONSULTANT',
    'FONSULTANT': 'CONSULTANT',
    'CONULTING': 'CONSULTING',
    'INVESTORB': 'INVESTOR',
    'INVESTORS': 'INVESTOR',
    'INVESTO': 'INVESTOR',
    'INVESTER': 'INVESTOR',
    'INVESMENTS': 'INVESTMENTS',
    'FINACE': 'FINANCE',
    'GINANCE': 'FINANCE',
    'MANAGERS': 'MANAGER',
    'MZNAGER': 'MANAGER',
    'PROPERTY MANGER': 'PROPERTY MANAGER',
    'PROJECT KANAGER': 'PROJECT MANAGER',
    'PORTFOLIO MANBAGER': 'PORTFOLIO MANAGER',
    'ASSET MANGER': 'ASSET MANAGER',
    'SALEA': 'SALES',
    'MARKERING': 'MARKETING',
    'MARKETIBG': 'MARKETING',
    'MARKRTING': 'MARKETING',
    'OWNERR': 'OWNER',
    'OWNEE': 'OWNER',
    'BUSINESS IWNER': 'BUSINESS OWNER',
    'BUSINESS OWNERR': 'BUSINESS OWNER',
    'SMALL BUSINESS OWNERS': 'SMALL BUSINESS OWNER',
    'SMALL BUSINESS OWNDER': 'SMALL BUSINESS OWNER',
    'FINANACIAL ADVISOR': 'FINANCIAL ADVISOR',
    'FINANCIAL ADVISORY': 'FINANCIAL ADVISOR',
    'HAIRMAN': 'CHAIRMAN',
    'PARTNET': 'PARTNER',
    'PARATNER': 'PARTNER',
    'MANAGIN PARTNER': 'MANAGING PARTNER',
    'PROESSOR': 'PROFESSOR',
    'PROFESOR': 'PROFESSOR',
    'PRICIPAL': 'PRINCIPAL',
    'DIRCTOR': 'DIRECTOR',
    'DIRECTLOR': 'DIRECTOR',
    'MANGAGING DIRECTOR': 'MANAGING DIRECTOR',
    'MANAGING DORECTOR': 'MANAGING DIRECTOR',
    'DEPUTY MANGING DIRECTOR': 'DEPUTY MANAGING DIRECTOR',
    'EXECUTIVE DIRECTORR': 'EXECUTIVE DIRECTOR',
    'BUSINEES': 'BUSINESS',
    'BUSYNESS': 'BUSINESS',
    'BUSINESS MAN': 'BUSINESSMAN',
    'PSYCOLOGIST': 'PSYCHOLOGIST',
    'PSYCHOLOGISTS': 'PSYCHOLOGIST',
    'PSYCHOLOGIS': 'PSYCHOLOGIST',
    'DEVEOPER': 'DEVELOPER',
    'DEVELOPET': 'DEVELOPER',
    'TEACYER': 'TEACHER',
    'VENTURE CAPITOL': 'VENTURE CAPITAL',
    'RELTOR': 'REALTOR',
    'ACCOYNTANT': 'ACCOUNTANT',
    'ADVOSOR': 'ADVISOR',
    'DVISOR': 'ADVISOR',
    'INVESTMENT ADVISER': 'INVESTMENT ADVISOR',
    'ART ADVISORY': 'ART ADVISOR',
    'ART ADVISER': 'ART ADVISOR',
    'TAX ADVISER': 'TAX ADVISOR',
    'PRIVAT EQUITY': 'PRIVATE EQUITY',
    'ENTREPRENUR': 'ENTREPRENEUR',
    'COFOUNDER': 'CO-FOUNDER',
    'CO FOUNDER': 'CO-FOUNDER',
    'CINTRACTOR': 'CONTRACTOR',
    'CONSTRUCTIOM': 'CONSTRUCTION',
    'WEALTH MANANGEMENT': 'WEALTH MANAGEMENT',
    'SOCIAL WORKET': 'SOCIAL WORKER',
    'ADMINISTRAOR': 'ADMINISTRATOR',
    'BUSINESS DEVELOPEMENT': 'BUSINESS DEVELOPMENT',
    'CHIEF DEVELOPMENT OFFIER': 'CHIEF DEVELOPMENT OFFICER',
    'TALENT AGWNT': 'TALENT AGENT',
    'FUND RAISER': 'FUNDRAISER',
    'RESTAURANTEUR': 'RESTAURATEUR',
    'AUTHOE': 'AUTHOR',
    'MEECHANT': 'MERCHANT',
    'CARDIOLODIST': 'CARDIOLOGIST',
    'PIDIATRIST': 'PODIATRIST',

    # batch 2
    'ATROENEY': 'ATTORNEY',
    'ATTOENY': 'ATTORNEY',
    "ATT'Y": 'ATTORNEY',
    'MARKEITNG': 'MARKETING',
    'HESLTHCARE': 'HEALTHCARE',
    'REAL EATSTE': 'REAL ESTATE',
    'PRODUCT MANAGEENT': 'PRODUCT MANAGEMENT',
    'FINACIAL': 'FINANCIAL',
    'AUTOMTIVE': 'AUTOMOTIVE',
    'CLEANNG SERVICE': 'CLEANING SERVICE',
    'MANAY': 'MANAGER',
    'CO PRES': 'CO-PRESIDENT',
    'AQUISITIONS': 'ACQUISITIONS',
    'JEWLERY': 'JEWELRY',
    'PHYT': 'PHYSICAL THERAPIST',
}


# Variant spellings of the same job title, applied by enhancements.
OCCUPATION_CANONICAL = {
    # medical
    'ORTHOPAEDIC SURGEON': 'ORTHOPEDIC SURGEON',
    'ORTHO SURGEON': 'ORTHOPEDIC SURGEON',
    'PODIATRIC PHYSICIAN': 'PODIATRIST',
    'PODIATRISY': 'PODIATRIST',
    'DENTISTY': 'DENTIST',
    'PHARMACETICALS': 'PHARMACIST',
    'PSYCHOTHERAPISTS': 'PSYCHOTHERAPIST',
    'CARDIOLOGISTS': 'CARDIOLOGIST',
    'RETINA SURGEONS': 'RETINA SURGEON',
    'SCHOOLPSYCHOLOGIST': 'SCHOOL PSYCHOLOGIST',
    # legal
    'ATTY': 'ATTORNEY',
    'ATTORNEY-AT-LAW': 'ATTORNEY',
    'ATTORNEY AT LAW': 'ATTORNEY',
    # finance
    'FINANCIAL ADVISER': 'FINANCIAL ADVISOR',
    'FINANCIAL ADVISOY': 'FINANCIAL ADVISOR',
    'FINANCIAL ADVISIR': 'FINANCIAL ADVISOR',
    'FINANCIAL ADV': 'FINANCIAL ADVISOR',
    'FINANCIAL SREVICES': 'FINANCIAL SERVICES',
    'INVESTMENT ADVISORS': 'INVESTMENT ADVISOR',
    # accounting
    'CERTIFIED PUBLIC ACCOUNTANT': 'CPA',
    'CERT. PUBLIC ACCOUNTANT': 'CPA',
    'CERIFIED PUBLIC ACCOUNTANT': 'CPA',
    'CERTIFIED PUBIC ACCOUNTANT': 'CPA',
    # engineering
    'SW ENGINEER': 'SOFTWARE ENGINEER',
    'SYSTEM ENGINEER': 'SYSTEMS ENGINEER',
    # real estate
    'RE DEVELOPER': 'REAL ESTATE DEVELOPER',
    'RE DEVELOPMENT': 'REAL ESTATE DEVELOPMENT',
    'RE FINANCE': 'REAL ESTATE FINANCE',
    'REAL ESTATE DEVELOPRR': 'REAL ESTATE DEVELOPER',
    'REAL ESTATE DECELOPET': 'REAL ESTATE DEVELOPER',
    'REAL ESTATE DRVELOPER': 'REAL ESTATE DEVELOPER',
    'REAL ESTATE DEVOLOPMENT': 'REAL ESTATE DEVELOPMENT',
    'REAL ESTATE INVESTER': 'REAL ESTATE INVESTOR',
    'REAL ESTATE INVEATOR': 'REAL ESTATE INVESTOR',
    'REAL ESTATE BROKET': 'REAL ESTATE BROKER',
    'REAL ESTATE DEV': 'REAL ESTATE DEVELOPER',
    'REAL ESTATE EXEC': 'REAL ESTATE EXECUTIVE',
    'REAL ESTATE MGMT': 'REAL ESTATE MANAGEMENT',
    'REAL ESTATE MGR': 'REAL ESTATE MANAGER',
    'COMERCIAL REAL ESTATE EXECUTIVE': 'COMMERCIAL REAL ESTATE EXECUTIVE',
    'COMMERICAL REAL ESTATE': 'COMMERCIAL REAL ESTATE',
    'COMMERCAIL REAL ESTATE EXECUTIVE': 'COMMERCIAL REAL ESTATE EXECUTIVE',
    'COMMERICAL REAL ESTATE LANDLORD': 'COMMERCIAL REAL ESTATE',
    # exec -> executive
    'BUSINESS EXEC': 'BUSINESS EXECUTIVE',
    'INSURANCE EXEC': 'INSURANCE EXECUTIVE',
    'FINANCIAL MGMT': 'FINANCIAL MANAGEMENT',
    # C-suite
    'C.E.O.': 'CEO', 'C.E.O': 'CEO',
    'CHIEF EXECUTIVE OFFICER': 'CEO',
    'CHIEF EXECUTIVE': 'CEO',
    'C.F.O.': 'CFO', 'C.F.O': 'CFO',
    'CHIEF FINANCIAL OFFICER': 'CFO',
    'C.O.O.': 'COO',
    'CHIEF OPERATING OFFICER': 'COO',
    'CHIEF TECHNOLOGY OFFICER': 'CTO',
    'CHIEF TECHNICAL OFFICER': 'CTO',
    # VP
    'VP': 'VICE PRESIDENT',
    'V.P.': 'VICE PRESIDENT',
    'VICE PRES': 'VICE PRESIDENT',
    'VICE-PRESIDENT': 'VICE PRESIDENT',
    'SVP': 'SENIOR VICE PRESIDENT',
    'EVP': 'EXECUTIVE VICE PRESIDENT',
    # other
    'ENTREPRENUER': 'ENTREPRENEUR',
    'DORECTOR': 'DIRECTOR',
    'PROJECTMANAGER': 'PROJECT MANAGER',
    'HOME MAKER': 'HOMEMAKER',
    'HOME-MAKER': 'HOMEMAKER',
    'NON-PROFIT': 'NONPROFIT',
    'NON PROFIT': 'NONPROFIT',
    'MGMT CONSULTANT': 'MANAGEMENT CONSULTANT',
}


# Raw occupation fixes that also assign a category.
OCCUPATION_FIXES = {
    # management
    'MGR': ('MANAGER', 'MANAGEMENT'),
    'MGMT': ('MANAGEMENT', 'MANAGEMENT'),
    'MGT': ('MANAGEMENT', 'MANAGEMENT'),
    'MGT.': ('MANAGEMENT', 'MANAGEMENT'),

    # tech
    'SW ENG': ('SOFTWARE ENGINEER', 'TECHNOLOGY'),
    'SWE': ('SOFTWARE ENGINEER', 'TECHNOLOGY'),
    'SDE': ('SOFTWARE DEVELOPMENT ENGINEER', 'TECHNOLOGY'),
    'SE': ('SOFTWARE ENGINEER', 'TECHNOLOGY'),
    'ENIGINEER': ('ENGINEER', 'TECHNOLOGY'),
    'ENGINNER': ('ENGINEER', 'TECHNOLOGY'),
    'ENFINEER': ('ENGINEER', 'TECHNOLOGY'),
    'DEV': ('SOFTWARE DEVELOPER', 'TECHNOLOGY'),
    'TECH': ('TECHNOLOGY', 'TECHNOLOGY'),

    # real estate
    'RE': ('REAL ESTATE', 'REAL ESTATE'),
    'REALESTATE': ('REAL ESTATE', 'REAL ESTATE'),
    'REALSTATE': ('REAL ESTATE', 'REAL ESTATE'),

    # finance
    'VC': ('VENTURE CAPITAL', 'FINANCE / INVESTMENT'),
    'PE': ('PRIVATE EQUITY', 'FINANCE / INVESTMENT'),
    'VENTURE': ('VENTURE CAPITAL', 'FINANCE / INVESTMENT'),
    'FIN': ('FINANCE', 'FINANCE / INVESTMENT'),
    'RIA': ('REGISTERED INVESTMENT ADVISOR', 'FINANCE / INVESTMENT'),
    'CFP': ('CFP', 'FINANCE / INVESTMENT'),  # credential, kept as-is
    'FA': ('FINANCIAL ADVISOR', 'FINANCE / INVESTMENT'),
    'CFA': ('CFA', 'FINANCE / INVESTMENT'),  # credential, kept as-is
    'PWA': ('PRIVATE WEALTH ADVISOR', 'FINANCE / INVESTMENT'),
    'M&A': ('MERGERS & ACQUISITIONS', 'FINANCE / INVESTMENT'),

    # medical
    'MD': ('MEDICAL DOCTOR', 'MEDICAL / HEALTHCARE'),
    'M.D.': ('MEDICAL DOCTOR', 'MEDICAL / HEALTHCARE'),
    'M.D': ('MEDICAL DOCTOR', 'MEDICAL / HEALTHCARE'),
    'M,D': ('MEDICAL DOCTOR', 'MEDICAL / HEALTHCARE'),
    'DR': ('DOCTOR', 'MEDICAL / HEALTHCARE'),
    'DR.': ('DOCTOR', 'MEDICAL / HEALTHCARE'),
    'DOC': ('DOCTOR', 'MEDICAL / HEALTHCARE'),
    'MED': ('MEDICAL DOCTOR', 'MEDICAL / HEALTHCARE'),
    'DDS': ('DDS', 'MEDICAL / HEALTHCARE'),  # credential, kept as-is
    'RN': ('REGISTERED NURSE', 'MEDICAL / HEALTHCARE'),
    'NP': ('NURSE PRACTITIONER', 'MEDICAL / HEALTHCARE'),
    'PT': ('PHYSICAL THERAPIST', 'MEDICAL / HEALTHCARE'),
    'RDH': ('DENTAL HYGIENIST', 'MEDICAL / HEALTHCARE'),
    'SLP': ('SPEECH LANGUAGE PATHOLOGIST', 'MEDICAL / HEALTHCARE'),
    'LMFT': ('LMFT', 'MEDICAL / HEALTHCARE'),  # credential, kept as-is

    # legal
    'ATTY': ('ATTORNEY', 'LEGAL'),
    'LAW': ('LAWYER', 'LEGAL'),
    'ATT': ('ATTORNEY', 'LEGAL'),

    # executive
    'CE0': ('CEO', 'EXECUTIVE / C-SUITE'),
    'CAO': ('CHIEF ADMINISTRATIVE OFFICER', 'EXECUTIVE / C-SUITE'),
    'CRO': ('CHIEF REVENUE OFFICER', 'EXECUTIVE / C-SUITE'),
    'CCO': ('CHIEF COMPLIANCE OFFICER', 'EXECUTIVE / C-SUITE'),
    'CPO': ('CHIEF PRODUCT OFFICER', 'EXECUTIVE / C-SUITE'),
    'CO CEO': ('CO-CEO', 'EXECUTIVE / C-SUITE'),
    'EXEC': ('EXECUTIVE', 'EXECUTIVE / C-SUITE'),
    'EXC': ('EXECUTIVE', 'EXECUTIVE / C-SUITE'),
    'PRES': ('PRESIDENT', 'EXECUTIVE / C-SUITE'),
    'DIR': ('DIRECTOR', 'EXECUTIVE / C-SUITE'),
    'NED': ('NON-EXECUTIVE DIRECTOR', 'EXECUTIVE / C-SUITE'),
    'VICE PRES': ('VICE PRESIDENT', 'EXECUTIVE / C-SUITE'),
    'VICE-PRES': ('VICE PRESIDENT', 'EXECUTIVE / C-SUITE'),
    'V.P.': ('VICE PRESIDENT', 'EXECUTIVE / C-SUITE'),
    'COB': ('CHAIRMAN', 'EXECUTIVE / C-SUITE'),  # Chairman of the Board
    'SUPERMARKET EXEC': ('SUPERMARKET EXECUTIVE', 'EXECUTIVE / C-SUITE'),

    # sales / marketing
    'AE': ('ACCOUNT EXECUTIVE', 'SALES / MARKETING'),
    'CSM': ('CUSTOMER SUCCESS MANAGER', 'SALES / MARKETING'),
    'BDM': ('BUSINESS DEVELOPMENT MANAGER', 'SALES / MARKETING'),
    'GSM': ('GLOBAL SALES MANAGER', 'SALES / MARKETING'),
    'PR': ('PUBLIC RELATIONS', 'SALES / MARKETING'),
    'MKTG': ('MARKETING', 'SALES / MARKETING'),
    # listed so the EXECUTIVE regex doesn't send these to C-SUITE
    'ACCOUNT EXECUTIVE': ('ACCOUNT EXECUTIVE', 'SALES / MARKETING'),
    'ACCOUNT EXEC': ('ACCOUNT EXECUTIVE', 'SALES / MARKETING'),

    'ADMIN': ('ADMINISTRATOR', 'MANAGEMENT'),
    'INV': ('INVESTOR', 'FINANCE / INVESTMENT'),
    'INS': ('INSURANCE', 'INSURANCE'),
    'BOSS': ('BUSINESS OWNER', 'BUSINESS / ENTREPRENEUR'),

    # education; NIST is context-dependent, handled in enhancements.py
    'TCHR': ('TEACHER', 'EDUCATION'),
    'PROF': ('PROFESSOR', 'EDUCATION'),

    # government / military
    'FSO': ('FOREIGN SERVICE OFFICER', 'GOVERNMENT / MILITARY'),
    'MP': ('MILITARY POLICE', 'GOVERNMENT / MILITARY'),
    'GR': ('GOVERNMENT RELATIONS', 'GOVERNMENT / MILITARY'),

    # other known
    'DBA': ('DATABASE ADMINISTRATOR', 'TECHNOLOGY'),
    'HR': ('HUMAN RESOURCES', 'MANAGEMENT'),
    'PM': ('PROJECT MANAGER', 'MANAGEMENT'),
    'AR': ('ACCOUNTS RECEIVABLE', 'ACCOUNTING / TAX'),
    'CTR': ('CONTRACTOR', 'CONSTRUCTION / TRADES'),
    'ART': ('ART', 'ARTS / ENTERTAINMENT'),
    'RABB': ('RABBI', 'RELIGIOUS'),
    'GIG': ('SELF-EMPLOYED', 'SELF-EMPLOYED'),
    'HW': ('HOMEMAKER', 'HOMEMAKER'),
    'NON': ('NONPROFIT', 'NONPROFIT / PHILANTHROPY'),
    'MC': ('MANAGEMENT CONSULTANT', 'CONSULTING'),
    'AVP': ('ASSISTANT VICE PRESIDENT', 'EXECUTIVE / C-SUITE'),
    'FOOD': ('FOOD', 'FOOD / HOSPITALITY'),

    # verified with employer context from real data
    'GEN MGR': ('GENERAL MANAGER', 'MANAGEMENT'),
    'GENL MGR': ('GENERAL MANAGER', 'MANAGEMENT'),
    'INV MGR': ('INVESTMENT MANAGER', 'FINANCE / INVESTMENT'),
    'EXECTUTIVE': ('EXECUTIVE', 'EXECUTIVE / C-SUITE'),

    # verified from real data
    'DEISGNER': ('DESIGNER', 'ARTS / ENTERTAINMENT'),
    'PHYSICAN': ('PHYSICIAN', 'MEDICAL / HEALTHCARE'),
    'PHYSICISN': ('PHYSICIAN', 'MEDICAL / HEALTHCARE'),
    'PHYSICAIN': ('PHYSICIAN', 'MEDICAL / HEALTHCARE'),
    'ATTORМEY': ('ATTORNEY', 'LEGAL'),  # Cyrillic М
    'ATTONREY': ('ATTORNEY', 'LEGAL'),
    'ATTORMEY': ('ATTORNEY', 'LEGAL'),
    'ATTORENY': ('ATTORNEY', 'LEGAL'),
    'ATORNEY': ('ATTORNEY', 'LEGAL'),
    'ATTOREY': ('ATTORNEY', 'LEGAL'),
    'CONSJLTANT': ('CONSULTANT', 'CONSULTING'),
    'COMSUJTANT': ('CONSULTANT', 'CONSULTING'),
    'CONSUTLANT': ('CONSULTANT', 'CONSULTING'),
    'COMSULTANT': ('CONSULTANT', 'CONSULTING'),
    'CONSLTANT': ('CONSULTANT', 'CONSULTING'),
    'REAL EATATE': ('REAL ESTATE', 'REAL ESTATE'),
    'REAL ESTSTE': ('REAL ESTATE', 'REAL ESTATE'),
    'WEALTH MANAGMENT': ('WEALTH MANAGEMENT', 'FINANCE / INVESTMENT'),

    # bare 'EMPLOYED' deliberately absent — left as OTHER so the AI classifier
    # sees it with employer context

    # from data analysis
    'DRIVING': ('DRIVING', 'TRANSPORTATION'),
    'MOVER': ('MOVER', 'TRANSPORTATION'),
    'INVESTING': ('INVESTING', 'FINANCE / INVESTMENT'),
    'MONEY': ('FINANCE', 'FINANCE / INVESTMENT'),
    'COMPLIANCE': ('COMPLIANCE', 'LEGAL'),
    'OWNER3': ('OWNER', 'BUSINESS / ENTREPRENEUR'),
    'REL ESTATE': ('REAL ESTATE', 'REAL ESTATE'),
    'PILATES': ('PILATES', 'FOOD / HOSPITALITY'),
    'FITNESS': ('FITNESS', 'FOOD / HOSPITALITY'),
    'ORALSURGERON': ('ORAL SURGEON', 'MEDICAL / HEALTHCARE'),
    'PSYCHOANALYST': ('PSYCHOANALYST', 'MEDICAL / HEALTHCARE'),
    'PHARMA': ('PHARMA', 'MEDICAL / HEALTHCARE'),
    'NURSING HOME': ('NURSING HOME', 'MEDICAL / HEALTHCARE'),
    'SHAREHOLDER': ('SHAREHOLDER', 'FINANCE / INVESTMENT'),
    'OFFICER': ('OFFICER', 'EXECUTIVE / C-SUITE'),
    'DESIGN': ('DESIGN', 'ARTS / ENTERTAINMENT'),
    'EDUCATION': ('EDUCATION', 'EDUCATION'),
    'OFFICE': ('OFFICE', 'MANAGEMENT'),
    'TRAINER': ('TRAINER', 'EDUCATION'),
    'AGENT': ('AGENT', 'SALES / MARKETING'),
    'TESTER': ('TESTER', 'TECHNOLOGY'),
    'ASSOCIATE': ('ASSOCIATE', 'MANAGEMENT'),
    'PROFESSIONAL': ('PROFESSIONAL', 'BUSINESS / ENTREPRENEUR'),

    # round 2
    'ATTOENEY': ('ATTORNEY', 'LEGAL'),
    'ATTORNET': ('ATTORNEY', 'LEGAL'),
    'LAWYET': ('LAWYER', 'LEGAL'),
    'LAWER': ('LAWYER', 'LEGAL'),
    'ATTORNE': ('ATTORNEY', 'LEGAL'),
    'ATTORNWY': ('ATTORNEY', 'LEGAL'),
    'ATTORNEU': ('ATTORNEY', 'LEGAL'),
    'CHSIRMSN': ('CHAIRMAN', 'EXECUTIVE / C-SUITE'),
    'PRINCIPLE': ('PRINCIPAL', 'EXECUTIVE / C-SUITE'),
    'REAL': ('REAL ESTATE', 'REAL ESTATE'),
    'BUS': ('BUSINESS', 'BUSINESS / ENTREPRENEUR'),
    'HEDGE FUND': ('HEDGE FUND', 'FINANCE / INVESTMENT'),
    'MONEY MGMT': ('MONEY MANAGEMENT', 'FINANCE / INVESTMENT'),
    'INV MGT': ('INVESTMENT MANAGEMENT', 'FINANCE / INVESTMENT'),
    'FUND MGR': ('FUND MANAGER', 'FINANCE / INVESTMENT'),
    'CREDIT REPORTING': ('CREDIT REPORTING', 'FINANCE / INVESTMENT'),
    'MORTGAGE': ('MORTGAGE', 'FINANCE / INVESTMENT'),
    'AUTO REPAIR': ('AUTO REPAIR', 'CONSTRUCTION / TRADES'),
    'RESTAURATEUR': ('RESTAURATEUR', 'FOOD / HOSPITALITY'),
    'JOURNALIST': ('JOURNALIST', 'ARTS / ENTERTAINMENT'),
    'BROADCASTING': ('BROADCASTING', 'ARTS / ENTERTAINMENT'),
    'MUSIC': ('MUSIC', 'ARTS / ENTERTAINMENT'),
    'ACUPUNCTURIST': ('ACUPUNCTURIST', 'MEDICAL / HEALTHCARE'),
    'MEDICINE': ('MEDICINE', 'MEDICAL / HEALTHCARE'),
    'ORTHOPAEDIC SURGERY': ('ORTHOPEDIC SURGEON', 'MEDICAL / HEALTHCARE'),
    'PSYCHOTHERAPY': ('PSYCHOTHERAPY', 'MEDICAL / HEALTHCARE'),
    'PSYCHOPHARMACOLOGIST': ('PSYCHOPHARMACOLOGIST', 'MEDICAL / HEALTHCARE'),
    'OPTOMETRY': ('OPTOMETRY', 'MEDICAL / HEALTHCARE'),
    'NURSING HOMES': ('NURSING HOMES', 'MEDICAL / HEALTHCARE'),
    'SPEECH THERAPY': ('SPEECH THERAPY', 'MEDICAL / HEALTHCARE'),
    'LIFE SCIENCES': ('LIFE SCIENCES', 'SCIENCE / RESEARCH'),
    'RESEARCH': ('RESEARCH', 'SCIENCE / RESEARCH'),
    'OIL AND GAS': ('OIL AND GAS', 'BUSINESS / ENTREPRENEUR'),
    'CARPET INDUSTRY': ('CARPET INDUSTRY', 'BUSINESS / ENTREPRENEUR'),
    'MATCHMAKER': ('MATCHMAKER', 'BUSINESS / ENTREPRENEUR'),
    'ENTREPENEUR': ('ENTREPRENEUR', 'BUSINESS / ENTREPRENEUR'),
    'PHILANTROPIST': ('PHILANTHROPIST', 'NONPROFIT / PHILANTHROPY'),
    'PUBLIC AFFAIRS': ('PUBLIC AFFAIRS', 'GOVERNMENT / MILITARY'),
    'LEGISLATIVE ADVOCATE': ('LEGISLATIVE ADVOCATE', 'GOVERNMENT / MILITARY'),
    'LAW ENFORCEMENT': ('LAW ENFORCEMENT', 'GOVERNMENT / MILITARY'),
    'POLICE DETECTIVE': ('POLICE DETECTIVE', 'GOVERNMENT / MILITARY'),
    'REAL ESTTE': ('REAL ESTATE', 'REAL ESTATE'),
    'REAL ESTATW': ('REAL ESTATE', 'REAL ESTATE'),
    'REAL EDTATE': ('REAL ESTATE', 'REAL ESTATE'),
    'REAL ESATE': ('REAL ESTATE', 'REAL ESTATE'),
    'REALESYATE': ('REAL ESTATE', 'REAL ESTATE'),
    'REAL ESSSSTATE': ('REAL ESTATE', 'REAL ESTATE'),
    'REALTOE': ('REAL ESTATE AGENT', 'REAL ESTATE'),
    'LANDSCAPING': ('LANDSCAPING', 'CONSTRUCTION / TRADES'),
    'RE DEVELOPMNET': ('REAL ESTATE DEVELOPER', 'REAL ESTATE'),
    'DIGITAL': ('DIGITAL', 'TECHNOLOGY'),

    # junk -> NOT DISCLOSED with NULL category (occupation_status set in occupations.py)
    'OCC': ('NOT DISCLOSED', None),
    'XXX': ('NOT DISCLOSED', None),
    'UGH': ('NOT DISCLOSED', None),
    'SDSDS': ('NOT DISCLOSED', None),
    'FDE': ('NOT DISCLOSED', None),
    'ZZZ': ('NOT DISCLOSED', None),
    'WHAT': ('NOT DISCLOSED', None),
    'ABC': ('NOT DISCLOSED', None),
    '3F': ('NOT DISCLOSED', None),
    'NB': ('NOT DISCLOSED', None),
    'JA.': ('NOT DISCLOSED', None),
    'IF': ('NOT DISCLOSED', None),
    'PO': ('NOT DISCLOSED', None),
    'IC': ('NOT DISCLOSED', None),
    'CX': ('NOT DISCLOSED', None),
    'PC': ('NOT DISCLOSED', None),
    'EBP': ('NOT DISCLOSED', None),
    'RPD': ('NOT DISCLOSED', None),
    '750,000': ('NOT DISCLOSED', None),
    'PIMP': ('NOT DISCLOSED', None),
    'SUPERHERO': ('NOT DISCLOSED', None),
    'EATING': ('NOT DISCLOSED', None),
    'HARD WORK': ('NOT DISCLOSED', None),
    'LOADING...': ('NOT DISCLOSED', None),
    'AN OCCUPATION': ('NOT DISCLOSED', None),
    'TKHOME': ('NOT DISCLOSED', None),
    'DONOR': ('NOT DISCLOSED', None),
    'WORKER': ('OTHER', 'OTHER'),  # too vague for a category, but employed
    'LABORER': ('LABORER', 'TRADES / LABOR'),
    'OTHER': ('NOT DISCLOSED', None),

    # veterinary
    'VETERINARIAN': ('VETERINARIAN', 'MEDICAL / HEALTHCARE'),
    'VETERINARY': ('VETERINARIAN', 'MEDICAL / HEALTHCARE'),
    'VET': ('VETERINARIAN', 'MEDICAL / HEALTHCARE'),
    'VETERINARY DOCTOR': ('VETERINARIAN', 'MEDICAL / HEALTHCARE'),
    'DVM': ('VETERINARIAN', 'MEDICAL / HEALTHCARE'),
    'VETERINARY SURGEON': ('VETERINARIAN', 'MEDICAL / HEALTHCARE'),

    # explicit refusals
    'PRIVATE': ('NOT DISCLOSED', None),
    'CONFIDENTIAL': ('NOT DISCLOSED', None),
    'MYOB': ('NOT DISCLOSED', None),
    'TMI': ('NOT DISCLOSED', None),
    'PREFER NOT TO ANSWER': ('NOT DISCLOSED', None),
    'DECLINED TO ANSWER': ('NOT DISCLOSED', None),

    # reclassifiable from OTHER
    'CFO': ('CFO', 'EXECUTIVE / C-SUITE'),
    'CHIEF FINANCIAL OFFICER': ('CFO', 'EXECUTIVE / C-SUITE'),
    'PR/EXEC': ('PR EXECUTIVE', 'EXECUTIVE / C-SUITE'),
    'CSO': ('CHIEF STRATEGY OFFICER', 'EXECUTIVE / C-SUITE'),
    'CH. BD': ('CHAIR OF THE BOARD', 'EXECUTIVE / C-SUITE'),
    'OFFICER IN COMPANY': ('OFFICER', 'EXECUTIVE / C-SUITE'),
    'MARKET VP': ('VP OF MARKETING', 'EXECUTIVE / C-SUITE'),
    'VP, RETAILER RELATIONS': ('VP RETAILER RELATIONS', 'EXECUTIVE / C-SUITE'),
    'GC': ('GENERAL COUNSEL', 'LEGAL'),
    'PARALEGAL': ('PARALEGAL', 'LEGAL'),
    'ART CONSULTATION': ('ART CONSULTANT', 'CONSULTING'),
    'POKER BROADCASTER': ('POKER BROADCASTER', 'ARTS / ENTERTAINMENT'),
    'RODEO CLOWN': ('RODEO CLOWN', 'ARTS / ENTERTAINMENT'),
    'DRAG QUEEN': ('DRAG QUEEN', 'ARTS / ENTERTAINMENT'),
    'ART DEALER': ('ART DEALER', 'ARTS / ENTERTAINMENT'),
    'MASTER TOUR GUIDE': ('MASTER TOUR GUIDE', 'ARTS / ENTERTAINMENT'),
    'CASHIER': ('CASHIER', 'FOOD / HOSPITALITY'),
    'BEER DISTRIBUTER': ('BEVERAGE DISTRIBUTOR', 'FOOD / HOSPITALITY'),
    'NUTRITIONIST': ('NUTRITIONIST', 'MEDICAL / HEALTHCARE'),
    'DIETITIAN': ('DIETITIAN', 'MEDICAL / HEALTHCARE'),
    'BEHAVIORAL HEALTH': ('BEHAVIORAL HEALTH', 'MEDICAL / HEALTHCARE'),
    'FOREIGN AFFAIRS OFFICER': ('FOREIGN AFFAIRS OFFICER', 'GOVERNMENT / MILITARY'),
    'SENATOR': ('SENATOR', 'GOVERNMENT / MILITARY'),
    'PROGRAM OFFICER': ('PROGRAM OFFICER', 'GOVERNMENT / MILITARY'),
    'GIFT BUYER': ('GIFT BUYER', 'SALES / MARKETING'),
    'LICENSING': ('LICENSING', 'SALES / MARKETING'),
    'COMMUNITY ENGAGEMENT': ('COMMUNITY ENGAGEMENT', 'SALES / MARKETING'),
    'COACH': ('COACH', 'EDUCATION'),
    'PERSONAL TRAINER': ('PERSONAL TRAINER', 'MEDICAL / HEALTHCARE'),
    'BOWLING PROPRIATOR': ('BOWLING PROPRIETOR', 'BUSINESS / ENTREPRENEUR'),
    'RD': ('RESEARCH & DEVELOPMENT', 'SCIENCE / RESEARCH'),
    'OWNERS REPRESENTATIVE': ('OWNERS REPRESENTATIVE', 'MANAGEMENT'),

    # single-character junk
    'A': ('NOT DISCLOSED', None),
    'E': ('NOT DISCLOSED', None),
    'N': ('NOT DISCLOSED', None),
    'R': ('NOT DISCLOSED', None),
    'V': ('NOT DISCLOSED', None),
    'XX': ('NOT DISCLOSED', None),

    # EMPLOYED without detail: employed but unspecified
    'EMPLOYED': ('EMPLOYED', None),

    # deep audit v4
    'ATTTORNEY': ('ATTORNEY', 'LEGAL'),
    'ATTNY': ('ATTORNEY', 'LEGAL'),
    'ATTORRNEY': ('ATTORNEY', 'LEGAL'),
    'ATTRONEY': ('ATTORNEY', 'LEGAL'),
    'ATTORNY': ('ATTORNEY', 'LEGAL'),
    'INSIRANCE': ('INSURANCE', 'INSURANCE'),
    'CHARIMAN': ('CHAIRMAN', 'EXECUTIVE / C-SUITE'),
    'EXECITIVE': ('EXECUTIVE', 'EXECUTIVE / C-SUITE'),
    'DESIGNSR': ('DESIGNER', 'ARTS / ENTERTAINMENT'),
    'PSYCHOLOGIDT': ('PSYCHOLOGIST', 'MEDICAL / HEALTHCARE'),
    'PSYCH': ('PSYCHOLOGIST', 'MEDICAL / HEALTHCARE'),
    'IDK': ('NOT DISCLOSED', None),
    'BAGMAN': ('NOT DISCLOSED', None),
    'PROPRIETOR': ('PROPRIETOR', 'BUSINESS / ENTREPRENEUR'),
    'REMODELING': ('REMODELER', 'CONSTRUCTION / TRADES'),
    'ADMISSIONS': ('ADMISSIONS', 'EDUCATION'),
    'LITERARY AGENT': ('LITERARY AGENT', 'ARTS / ENTERTAINMENT'),
    'MERCHANDISER': ('MERCHANDISER', 'SALES / MARKETING'),
    'THEATER PRODUCING': ('THEATER PRODUCER', 'ARTS / ENTERTAINMENT'),
}


# Explicit refusals keep NOT DISCLOSED; other fixes to that value are junk.
OCCUPATION_REFUSAL_INPUTS = frozenset({
    'PRIVATE', 'CONFIDENTIAL', 'PREFER NOT TO ANSWER',
    'DECLINED TO ANSWER', 'MYOB', 'TMI',
})

# Employer status -> occupation/category when occupation is missing.
OCCUPATION_FROM_EMPLOYER = {
    'RETIRED': ('RETIRED', 'RETIRED'),
    'SELF-EMPLOYED': ('SELF-EMPLOYED', 'SELF-EMPLOYED'),
    'NOT EMPLOYED': ('NOT EMPLOYED', 'NOT EMPLOYED'),
}

# Occupation status -> employer during the field-level pass.
EMPLOYER_FROM_OCCUPATION = {
    'RETIRED': 'RETIRED',
    'NOT EMPLOYED': 'NOT EMPLOYED',
    'HOMEMAKER': 'NOT EMPLOYED',
    'SELF-EMPLOYED': 'SELF-EMPLOYED',
    'STUDENT': 'STUDENT',
}

# Post-merge keeps homemaker as its own employer status and handles aliases.
POST_MERGE_EMPLOYER_FROM_OCCUPATION = {
    **EMPLOYER_FROM_OCCUPATION,
    'HOMEMAKER': 'HOMEMAKER',
    'HOUSEWIFE': 'HOMEMAKER',
    'UNEMPLOYED': 'NOT EMPLOYED',
}
EMPLOYER_FROM_CATEGORY = {
    category: POST_MERGE_EMPLOYER_FROM_OCCUPATION[category]
    for category in ('RETIRED', 'NOT EMPLOYED', 'HOMEMAKER', 'STUDENT', 'SELF-EMPLOYED')
}

SWAP_JOB_TITLES = _OCCUPATION_AS_EMPLOYER | frozenset({
    'MANAGER', 'PARTNER', 'ADMINISTRATOR',
    'PRESIDENT', 'VICE PRESIDENT', 'DIRECTOR', 'EXECUTIVE',
    'OFFICER', 'CEO', 'CFO', 'COO', 'CTO', 'CMO',
})

OCCUPATION_KEYWORDS = _OCCUPATION_AS_EMPLOYER | frozenset({
    'ATTORNEY', 'LAWYER', 'PARTNER', 'MANAGER', 'ADMINISTRATOR',
    'PRESIDENT', 'DIRECTOR', 'EXECUTIVE', 'PHYSICIAN', 'ACCOUNTANT',
    'CONSULTANT', 'ENGINEER', 'OFFICER', 'ANALYST', 'ADVISOR',
    'COUNSEL', 'DENTIST', 'SURGEON', 'BROKER', 'AGENT',
    'CLAIMS', 'CPA', 'OWNER', 'MANAGING PARTNER', 'MANAGING DIRECTOR',
    'PAC MANAGER', 'INSURANCE BROKER', 'INSURANCE AGENT', 'REAL ESTATE',
    'INVESTMENT MANAGEMENT', 'FINANCE', 'MARKETING', 'MANAGEMENT',
    'SALES', 'CASHIER', 'DESIGNER', 'CATER', 'CATERER', 'WRITER',
    'ARTIST', 'PSYCHOLOGIST', 'THERAPIST', 'PROFESSOR',
})

FINAL_SHORT_OCCUPATIONS = frozenset({
    'MD', 'VP', 'PA', 'RN', 'IT', 'PR', 'HR', 'AI', 'DJ', 'DO', 'GP', 'GM',
})
FINAL_JUNK_EMPLOYERS = frozenset({
    'VARIOUS', 'JOB', 'A', 'EMP', 'N', 'MULTIPLE', 'OTHER',
})
FINAL_NULL_EMPLOYERS = _REFUSAL_EMPLOYERS | frozenset({
    'N/A', 'NA', 'N A', 'NONE', 'NOT APPLICABLE', 'NOT APPLICAABLE',
    'NOT DISCLOSED', 'INFORMATION REQUESTED',
    'INFORMATION REQUESTED PER BEST EFFORTS', 'PHYSICAN', 'SELP EMPLOYED',
})
WEB_ARTIFACT_OCCUPATIONS = frozenset({'LOADING', 'ACMIO', 'REMD', 'SWAP MEET'})

KNOWN_COMPANY_OCCUPATIONS = frozenset({
    'ARCH INSURANCE', 'BROWN & BROWN', 'DANZIGER & DE LLANO LLP',
    'NNA SERVICES LLC', 'BAKER TILLY', 'AMERICAN EXPRESS',
    'NFI INDUSTRIES', 'SKYRISE PROPERTIES', 'PAYROLL COMPANY',
})

HOMEMAKER_EMPLOYER_VALUES = frozenset({
    'HOMEMAKER', 'HOUSEWIFE', 'HOUSWIFE', 'HOUSEWIVES',
    'STAY AT HOME MOM', 'STAY AT HOME DAD',
})
EMPLOYER_TYPO_FIXES = (
    (r'ASSOCAITE', 'ASSOCIATE'),
    (r'ASSOICATE', 'ASSOCIATE'),
    (r'ASOCIATE', 'ASSOCIATE'),
    (r'DERMATOLOGITS\b', 'DERMATOLOGISTS'),
    (r'MANAGMENT', 'MANAGEMENT'),
    (r'MANAGEMNT', 'MANAGEMENT'),
    (r'INVESTEMENT', 'INVESTMENT'),
)
