"""Focused record-level safety rules, in one declared order."""
from fec.cleaning.audit_trail import (
    EMPLOYMENT_FIELDS,
    NAME_FIELDS,
    PEOPLE_FIELDS,
    PLACE_FIELDS,
    WORK_FIELDS,
)

from .addresses import (
    _fill_null_city_from_zip,
    _fix_foreign_addresses,
    _fix_garbage_city_names,
    _fix_pr_zip_wrong_state,
)
from .committee import (
    _fix_committee_employer,
    _fix_misclassified_foundation,
    _fix_title_as_first_name,
)
from .employer import (
    _clear_admin_note_employers,
    _clear_refusal_employers,
    _fix_choose_prefix,
    _fix_email_employer_final,
    _fix_junk_employer_patterns,
    _fix_numeric_employer_final,
    _fix_retired_typos,
    _fix_truncated_employer_38,
    _null_sector_as_employer,
    _null_short_employer_junk,
)
from .employer_swaps import (
    _fix_company_name_as_occupation,
    _fix_employer_equals_occupation,
    _fix_employer_is_occupation_word,
    _fix_occ_emp_both_swapped,
    _fix_own_name_as_employer,
    _fix_role_as_employer,
    _fix_self_employed_consistency,
    _fix_swapped_emp_occ_company,
    _swap_role_employer_with_known_company,
)
from .occupation_context import _disambiguate_vague_occupation
from .occupation import (
    _fill_null_occupation_category,
    _fix_bitton_edge_case,
    _fix_disclosed_no_employer,
    _fix_emp_occ_category_consistency,
    _fix_employed_as_occupation,
    _fix_employed_no_category,
    _fix_not_disclosed_with_real_occ,
    _fix_slash_occupation,
    _fix_status_word_in_occupation,
    _fix_web_artifact_occupation,
    _null_junk_occupation,
    _reclassify_other_category,
)

ALL_ROWS = "all"
INDIVIDUALS = "individuals"
NON_INDIVIDUALS = "non_individuals"

# (rule, scope, fields it writes, audit reason)
SAFETY_RULES = (
    (_fix_committee_employer, NON_INDIVIDUALS, WORK_FIELDS,
     'committee_employer_cleared'),
    (_fix_disclosed_no_employer, ALL_ROWS, WORK_FIELDS,
     'disclosed_without_employer_status_fixed'),
    (_fix_employed_no_category, ALL_ROWS, WORK_FIELDS,
     'employed_occupation_category_other'),
    (_fix_status_word_in_occupation, INDIVIDUALS, WORK_FIELDS,
     'status_word_occupation_not_applicable'),
    (_fix_not_disclosed_with_real_occ, INDIVIDUALS, WORK_FIELDS,
     'not_disclosed_with_real_occupation_status_fixed'),
    (_fill_null_occupation_category, INDIVIDUALS, WORK_FIELDS,
     'null_occupation_category_filled'),
    (_fill_null_city_from_zip, ALL_ROWS, PLACE_FIELDS,
     'city_filled_from_zip'),
    (_fix_bitton_edge_case, INDIVIDUALS, WORK_FIELDS,
     'not_disclosed_self_employed_contradiction_fixed'),
    (_clear_refusal_employers, INDIVIDUALS, WORK_FIELDS,
     'refusal_placeholder_employer_nulled'),
    (_clear_admin_note_employers, INDIVIDUALS, WORK_FIELDS,
     'admin_note_employer_nulled'),
    (_null_short_employer_junk, INDIVIDUALS, WORK_FIELDS,
     'short_employer_junk_nulled'),
    (_fix_numeric_employer_final, INDIVIDUALS, WORK_FIELDS,
     'numeric_employer_nulled'),
    (_fix_email_employer_final, INDIVIDUALS, WORK_FIELDS,
     'email_in_employer_nulled'),
    (_fix_junk_employer_patterns, INDIVIDUALS, WORK_FIELDS,
     'repeated_char_employer_nulled'),
    (_fix_retired_typos, INDIVIDUALS, EMPLOYMENT_FIELDS,
     'retired_variant_normalized_or_tail_split_to_previous_employer'),
    (_fix_employer_equals_occupation, INDIVIDUALS, WORK_FIELDS,
     'employer_equals_occupation_self_employed'),
    (_fix_employer_is_occupation_word, INDIVIDUALS, WORK_FIELDS,
     'occupation_word_in_employer_resolved'),
    (_fix_misclassified_foundation, ALL_ROWS, PEOPLE_FIELDS,
     'org_parsed_as_person_reclassified'),
    (_fix_title_as_first_name, ALL_ROWS, NAME_FIELDS,
     'title_as_first_name_cleared'),
    (_fix_choose_prefix, ALL_ROWS, WORK_FIELDS,
     'choose_prefix_stripped'),
    # Preserve the real company before a bare role becomes SELF-EMPLOYED.
    (_swap_role_employer_with_known_company, ALL_ROWS, WORK_FIELDS,
     'role_employer_swapped_with_known_company'),
    (_fix_role_as_employer, ALL_ROWS, WORK_FIELDS,
     'role_as_employer_swapped_or_self_employed'),
    (_null_sector_as_employer, ALL_ROWS, WORK_FIELDS,
     'sector_word_employer_nulled'),
    (_fix_self_employed_consistency, ALL_ROWS, WORK_FIELDS,
     'self_employed_row_employer_normalized'),
    (_fix_own_name_as_employer, ALL_ROWS, WORK_FIELDS,
     'own_name_employer_self_employed'),
    (_fix_foreign_addresses, ALL_ROWS, PLACE_FIELDS,
     'foreign_city_us_state_mismatch_nulled'),
    (_fix_garbage_city_names, ALL_ROWS, PLACE_FIELDS,
     'garbage_city_name_nulled'),
    (_fix_pr_zip_wrong_state, ALL_ROWS, PLACE_FIELDS,
     'state_corrected_from_pr_vi_zip'),
    (_fix_truncated_employer_38, ALL_ROWS, WORK_FIELDS,
     'truncated_employer_expanded'),
    (_fix_company_name_as_occupation, ALL_ROWS, WORK_FIELDS,
     'company_in_occupation_moved_to_employer'),
    (_fix_swapped_emp_occ_company, ALL_ROWS, WORK_FIELDS,
     'job_title_employer_company_occupation_swapped'),
    (_fix_occ_emp_both_swapped, ALL_ROWS, WORK_FIELDS,
     'curated_company_in_occupation_swapped'),
    (_fix_web_artifact_occupation, ALL_ROWS, WORK_FIELDS,
     'web_artifact_occupation_nulled'),
    (_null_junk_occupation, ALL_ROWS, WORK_FIELDS,
     'email_or_company_in_occupation_moved_or_nulled'),
    (_fix_employed_as_occupation, ALL_ROWS, WORK_FIELDS,
     'employed_occupation_resolved'),
    (_fix_emp_occ_category_consistency, ALL_ROWS, WORK_FIELDS,
     'employer_occupation_category_consistency_fixed'),
    (_disambiguate_vague_occupation, ALL_ROWS, WORK_FIELDS,
     'vague_occupation_specialised_from_employer_context'),
    (_fix_slash_occupation, ALL_ROWS, WORK_FIELDS,
     'slash_occupation_recategorized'),
    (_reclassify_other_category, ALL_ROWS, WORK_FIELDS,
     'other_category_reclassified'),
)
